### ISSUE TITLE
[Bug] webview Lower than Expected on Android 12

### ISSUE THREAD

**Issue by Kyrieze** [Jays2Kings/tachiyomiJ2K#1126]
### Device information
* Tachiyomi version: 1.4.4
* Android phone & version: Android 12

## Steps to reproduce
1. Refresh Global Update 
2. Wait and it's take too long to refresh the list and grab the images instead using browser mode after open in webview

### Expected behavior
Normal as It should have been
### Actual behavior
Slow and sluggish 

### Other details

App version: 1.4.4 (standard, af77722f6, 86, 2021-12-21T20:12:28.0641618)
Android version: 12 (SDK 31)
Android build ID: SQ1A.211205.008
Device brand: google
Device manufacturer: Google
Device name: redfin
Device model: Pixel 5
Device product name: redfin--------- beginning of crash
12-27 15:39:52.570 17916 17916 E AndroidRuntime: FATAL EXCEPTION: main
12-27 15:39:52.570 17916 17916 E AndroidRuntime: Process: eu.kanade.tachiyomi.j2k, PID: 17916
12-27 15:39:52.570 17916 17916 E AndroidRuntime: java.lang.RuntimeException: Unable to create application eu.kanade.tachiyomi.App: android.util.AndroidRuntimeException: android.util.AndroidRuntimeException: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to verify WebView provider, version code is lower than expected: 466410434 actual: 447211483
12-27 15:39:52.570 17916 17916 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6730)
12-27 15:39:52.570 17916 17916 E AndroidRuntime: 	at android.app.ActivityThread.access$1500(ActivityThread.java:247)
12-27 15:39:52.570 17916 17916 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2053)
12-27 15:39:52.570 17916 17916 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
12-27 15:39:52.570 17916 17916 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
12-27 15:39:52.570 17916 17916 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
12-27 15:39:52.570 17916 17916 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7839)
12-27 15:39:52.570 17916 17916 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-27 15:39:52.570 17916 17916 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
12-27 15:39:52.570 17916 17916 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
12-27 15:39:52.570 17916 17916 E AndroidRuntime: Caused by: android.util.AndroidRuntimeException: android.util.AndroidRuntimeException: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to verify WebView provider, version code is lower than expected: 466410434 actual: 447211483
12-27 15:39:52.570 17916 17916 E AndroidRuntime: 	at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:363)
12-27 15:39:52.570 17916 17916 E AndroidRuntime: 	at android.webkit.CookieManager.getInstance(CookieManager.java:50)
12-27 15:39:52.570 17916 17916 E AndroidRuntime: 	at eu.kanade.tachiyomi.network.AndroidCookieJar.<init>(AndroidCookieJar.kt:10)
12-27 15:39:52.570 17916 17916 E AndroidRuntime: 	at eu.kanade.tachiyomi.network.NetworkHelper.<init>(NetworkHelper.kt:22)
12-27 15:39:52.570 17916 17916 E AndroidRuntime: 	at eu.kanade.tachiyomi.AppModule$registerInjectables$5.invoke(AppModule.kt:38)
12-27 15:39:52.570 17916 17916 E AndroidRuntime: 	at eu.kanade.tachiyomi.AppModule$registerInjectables$5.invoke(AppModule.kt:38)
12-27 15:39:52.570 17916 17916 E AndroidRuntime: 	at uy.kohesive.injekt.registry.default.DefaultRegistrar$addSingletonFactory$1$$special$$inlined$getOrPut$lambda$1.invoke(DefaultRegistrar.kt:49)
12-27 15:39:52.570 17916 17916 E AndroidRuntime: 	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
12-27 15:39:52.570 17916 17916 E AndroidRuntime: 	at uy.kohesive.injekt.registry.default.DefaultRegistrar$addSingletonFactory$1.invoke(DefaultRegistrar.kt:173)
12-27 15:39:52.570 17916 17916 E AndroidRuntime: 	at uy.kohesive.injekt.registry.default.DefaultRegistrar.getInstance(DefaultRegistrar.kt:103)
12-27 15:39:52.570 17916 17916 E AndroidRuntime: 	at uy.kohesive.injekt.api.InjektScope.getInstance(Unknown Source:7)
12-27 15:39:52.570 17916 17916 E AndroidRuntime: 	at eu.kanade.tachiyomi.data.image.coil.MangaFetcher.<init>(MangaFetcher.kt:193)
12-27 15:39:52.570 17916 17916 E AndroidRuntime: 	at eu.kanade.tachiyomi.data.image.coil.CoilSetup.<init>(CoilSetup.kt:28)
12-27 15:39:52.570 17916 17916 E AndroidRuntime: 	at eu.kanade.tachiyomi.App.onCreate(App.kt:65)
12-27 15:39:52.570 17916 17916 E AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1255)
12-27 15:39:52.570 17916 17916 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6725)
12-27 15:39:52.570 17916 17916 E AndroidRuntime: 	... 9 more
12-27 15:39:52.570 17916 17916 E AndroidRuntime: Caused by: android.util.AndroidRuntimeException: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to verify WebView provider, version code is lower than expected: 466410434 actual: 447211483
12-27 15:39:52.570 17916 17916 E AndroidRuntime: 	at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:532)
12-27 15:39:52.570 17916 17916 E AndroidRuntime: 	at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:348)
12-27 15:39:52.570 17916 17916 E AndroidRuntime: 	... 24 more
12-27 15:39:52.570 17916 17916 E AndroidRuntime: Caused by: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to verify WebView provider, version code is lower than expected: 466410434 actual: 447211483
12-27 15:39:52.570 17916 17916 E AndroidRuntime: 	at android.webkit.WebViewFactory.verifyPackageInfo(WebViewFactory.java:401)
12-27 15:39:52.570 17916 17916 E AndroidRuntime: 	at android.webkit.WebViewFactory.getWebViewContextAndSetProvider(WebViewFactory.java:461)
12-27 15:39:52.570 17916 17916 E AndroidRuntime: 	at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:493)
12-27 15:39:52.570 17916 17916 E AndroidRuntime: 	... 25 more

**Comment by Jays2Kings** [comment]
Clearly just sounds like you need to update your webview version

**Comment by Kyrieze** [comment]
I've got latest webview version, it's works fine in the original tachiyomi tho
