### ISSUE TITLE
Specific Page of Specific Chapter of a Specific Manga crashes the reader and forces you back to chapter selection screen

### ISSUE THREAD

**Issue by saschahi** [Jays2Kings/tachiyomiJ2K#1317]
### Steps to reproduce

1. Download Reaper Scans Extension
2. Open "I Obtained a Mythic Item - Manhwa"
3. Open Chapter 4, Page 7
4. Crash

### Expected behavior

Should show the page normally

### Actual behavior

Crashes

### Crash logs

App version: 1.5.4 (standard, 75c9b27d8, 92, 2022-05-23T18:09Z)
Android version: 10 (SDK 29)
Android build ID: STK-L21 10.0.0.208(C431E8R1P2)
Device brand: HUAWEI
Device manufacturer: HUAWEI
Device name: HWSTK-HF
Device model: STK-LX1
Device product name: STK-L21EEA

--------- beginning of crash
05-02 05:57:57.290  4667  4667 E AndroidRuntime: FATAL EXCEPTION: main
05-02 05:57:57.290  4667  4667 E AndroidRuntime: Process: eu.kanade.tachiyomi.j2k, PID: 4667
05-02 05:57:57.290  4667  4667 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.app.Activity.isTopOfTask()' on a null object reference
05-02 05:57:57.290  4667  4667 E AndroidRuntime: 	at android.app.ExitTransitionCoordinator.notifyComplete(ExitTransitionCoordinator.java:437)
05-02 05:57:57.290  4667  4667 E AndroidRuntime: 	at android.app.ExitTransitionCoordinator.onReceiveResult(ExitTransitionCoordinator.java:91)
05-02 05:57:57.290  4667  4667 E AndroidRuntime: 	at android.os.ResultReceiver$MyRunnable.run(ResultReceiver.java:50)
05-02 05:57:57.290  4667  4667 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:888)
05-02 05:57:57.290  4667  4667 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
05-02 05:57:57.290  4667  4667 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:213)
05-02 05:57:57.290  4667  4667 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8178)
05-02 05:57:57.290  4667  4667 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-02 05:57:57.290  4667  4667 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
05-02 05:57:57.290  4667  4667 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
06-02 20:27:57.039 11019 11019 E AndroidRuntime: FATAL EXCEPTION: main
06-02 20:27:57.039 11019 11019 E AndroidRuntime: Process: eu.kanade.tachiyomi.j2k, PID: 11019
06-02 20:27:57.039 11019 11019 E AndroidRuntime: java.lang.NullPointerException
06-02 20:27:57.039 11019 11019 E AndroidRuntime: 	at eu.kanade.tachiyomi.util.view.ControllerExtensionsKt$$ExternalSyntheticLambda2.run(R8$$SyntheticClass:3)
06-02 20:27:57.039 11019 11019 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:888)
06-02 20:27:57.039 11019 11019 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
06-02 20:27:57.039 11019 11019 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:213)
06-02 20:27:57.039 11019 11019 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8178)
06-02 20:27:57.039 11019 11019 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-02 20:27:57.039 11019 11019 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
06-02 20:27:57.039 11019 11019 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
06-07 20:21:07.833 10124 10124 E AndroidRuntime: FATAL EXCEPTION: main
06-07 20:21:07.833 10124 10124 E AndroidRuntime: Process: eu.kanade.tachiyomi.j2k, PID: 10124
06-07 20:21:07.833 10124 10124 E AndroidRuntime: java.lang.NullPointerException
06-07 20:21:07.833 10124 10124 E AndroidRuntime: 	at eu.kanade.tachiyomi.util.view.ControllerExtensionsKt$$ExternalSyntheticLambda2.run(R8$$SyntheticClass:3)
06-07 20:21:07.833 10124 10124 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:888)
06-07 20:21:07.833 10124 10124 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
06-07 20:21:07.833 10124 10124 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:213)
06-07 20:21:07.833 10124 10124 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8178)
06-07 20:21:07.833 10124 10124 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-07 20:21:07.833 10124 10124 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
06-07 20:21:07.833 10124 10124 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
--------- beginning of system
--------- beginning of main
06-28 13:35:51.032  3748  3748 E e.tachiyomi.j2: Not starting debugger since process cannot load the jdwp agent.
06-28 13:35:51.042  3748  3748 E libc    : Access denied finding property "runtime.mmitest.isrunning"
06-28 13:35:51.266  3748  3788 E AwareLog: AtomicFileUtils: readFileLines file not exist: android.util.AtomicFile@b0fec83
06-28 13:35:51.267  3748  3788 E AwareLog: AtomicFileUtils: readFileLines file not exist: android.util.AtomicFile@29ce00
06-28 13:36:02.620  3748  3860 E         : APS:IFLoad:importExternalFunctions, search function createNewHwApsUtils failed, dlsym err:undefined symbol: createNewHwApsUtils

### TachiyomiJ2K version

1.5.4

### Android version

Android 10

### Device

Huawei P Smart Z

### Other details

If this is an issue with the extension, I'm sorry. 
but from my perspective it seems to be an issue with the reader in general and the crashlog really doesn't help me out here.

This is the only page/chapter that this ever happened to me.

The Page loads correctly in webview and on firefox and doesn't seem corrupted.

I've asked in the tachiyomi Discord if someone else can recreate this and somad#0712 answered me that this same crash happens for them too.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Tachiyomi](https://github.com/tachiyomiorg/tachiyomi)
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.5.4](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have updated all installed extensions.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by saschahi** [comment]
apparently known issue according to jay

>It's already been reported before in this channel, turn on auto split tall images in download settings
