### ISSUE TITLE
App crashes then clears library after restoring from backup.

### ISSUE THREAD

**Issue by rajbahakdanyu** [Jays2Kings/tachiyomiJ2K#1322]
### Steps to reproduce

1. Restore backup.
[tachiyomi_2022-07-03_19-53.proto.gz](https://github.com/Jays2Kings/tachiyomiJ2K/files/9036563/tachiyomi_2022-07-03_19-53.proto.gz)

### Expected behavior

The app should crash and the restored data should be deleted.

### Actual behavior

App crashes after a successful restore then when you reopen the application the library will be empty.

### Crash logs

App version: 1.5.4 (standard, 75c9b27d8, 92, 2022-05-23T18:09Z)
Android version: 12 (SDK 32)
Android build ID: SQ3A.220605.009.B1
Device brand: Xiaomi
Device manufacturer: Xiaomi
Device name: sweet
Device model: M2101K6G
Device product name: aosp_sweet

--------- beginning of main
07-04 11:10:04.081 28819  2982 E SQLiteLog: (11) database corruption at line 67339 of [5c9a6c0687]
07-04 11:10:04.082 28819  2982 E SQLiteLog: (11) database corruption at line 67489 of [5c9a6c0687]
07-04 11:10:04.082 28819  2982 E SQLiteLog: (11) statement aborts at 22: [SELECT M.*, COALESCE(MC.category_id, 0) AS category
07-04 11:10:04.082 28819  2982 E SQLiteLog:     FROM (
07-04 11:10:04.082 28819  2982 E SQLiteLog:         SELECT mangas.*, COALESCE(C.unread, 0) AS unread, COALESCE(R.hasread, 0) AS has_read
07-04 11:10:04.082 28819  2982 E SQLiteLog:         FROM mangas
07-04 11:10:04.082 28819  2982 E SQLiteLog:         
07-04 11:10:04.082 28819  2982 E SupportSQLite: Corruption reported by sqlite on database: /data/user/0/eu.kanade.tachiyomi.j2k/databases/tachiyomi.db
07-04 11:10:04.111 28819  2982 E ACRA    : ACRA caught a StorIOException for eu.kanade.tachiyomi.j2k
07-04 11:10:04.111 28819  2982 E ACRA    : com.pushtorefresh.storio.StorIOException: Error has occurred during Get operation. query = RawQuery{query='
07-04 11:10:04.111 28819  2982 E ACRA    :     SELECT M.*, COALESCE(MC.category_id, 0) AS category
07-04 11:10:04.111 28819  2982 E ACRA    :     FROM (
07-04 11:10:04.111 28819  2982 E ACRA    :         SELECT mangas.*, COALESCE(C.unread, 0) AS unread, COALESCE(R.hasread, 0) AS has_read
07-04 11:10:04.111 28819  2982 E ACRA    :         FROM mangas
07-04 11:10:04.111 28819  2982 E ACRA    :         LEFT JOIN (
07-04 11:10:04.111 28819  2982 E ACRA    :             SELECT manga_id, COUNT(*) AS unread
07-04 11:10:04.111 28819  2982 E ACRA    :             FROM chapters
07-04 11:10:04.111 28819  2982 E ACRA    :             WHERE read = 0
07-04 11:10:04.111 28819  2982 E ACRA    :             GROUP BY manga_id
07-04 11:10:04.111 28819  2982 E ACRA    :         ) AS C
07-04 11:10:04.111 28819  2982 E ACRA    :         ON _id = C.manga_id
07-04 11:10:04.111 28819  2982 E ACRA    :         LEFT JOIN (
07-04 11:10:04.111 28819  2982 E ACRA    :             SELECT manga_id, COUNT(*) AS hasread
07-04 11:10:04.111 28819  2982 E ACRA    :             FROM chapters
07-04 11:10:04.111 28819  2982 E ACRA    :             WHERE read = 1
07-04 11:10:04.111 28819  2982 E ACRA    :             GROUP BY manga_id
07-04 11:10:04.111 28819  2982 E ACRA    :         ) AS R
07-04 11:10:04.111 28819  2982 E ACRA    :         ON _id = R.manga_id
07-04 11:10:04.111 28819  2982 E ACRA    :         WHERE favorite = 1
07-04 11:10:04.111 28819  2982 E ACRA    :         GROUP BY _id
07-04 11:10:04.111 28819  2982 E ACRA    :         ORDER BY title
07-04 11:10:04.111 28819  2982 E ACRA    :     ) AS M
07-04 11:10:04.111 28819  2982 E ACRA    :     LEFT JOIN (
07-04 11:10:04.111 28819  2982 E ACRA    :         SELECT * FROM mangas_categories) AS MC
07-04 11:10:04.111 28819  2982 E ACRA    :         ON MC.manga_id = M._id
07-04 11:10:04.111 28819  2982 E ACRA    : ', args=[], affectsTables=[], affectsTags=[], observesTables=[mangas_categories, categories, mangas, chapters], observesTags=[]}
07-04 11:10:04.111 28819  2982 E ACRA    : 	at com.pushtorefresh.storio.sqlite.operations.get.PreparedGetListOfObjects.executeAsBlocking(PreparedGetListOfObjects.java:22)
07-04 11:10:04.111 28819  2982 E ACRA    : 	at eu.kanade.tachiyomi.ui.library.LibraryPresenter.access$getLibraryFromDB(LibraryPresenter.kt:7)
07-04 11:10:04.111 28819  2982 E ACRA    : 	at eu.kanade.tachiyomi.ui.library.LibraryPresenter$getLibrary$2$library$1.invokeSuspend(Unknown Source:8)
07-04 11:10:04.111 28819  2982 E ACRA    : 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
07-04 11:10:04.111 28819  2982 E ACRA    : 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
07-04 11:10:04.111 28819  2982 E ACRA    : 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:2)
07-04 11:10:04.111 28819  2982 E ACRA    : 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:1)
07-04 11:10:04.111 28819  2982 E ACRA    : 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
07-04 11:10:04.111 28819  2982 E ACRA    : 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:10)
07-04 11:10:04.111 28819  2982 E ACRA    : 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@e115fc8, Dispatchers.Default]
07-04 11:10:04.111 28819  2982 E ACRA    : Caused by: android.database.sqlite.SQLiteDatabaseCorruptException: database disk image is malformed (code 11)
07-04 11:10:04.111 28819  2982 E ACRA    : 	at io.requery.android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
07-04 11:10:04.111 28819  2982 E ACRA    : 	at io.requery.android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:8)
07-04 11:10:04.111 28819  2982 E ACRA    : 	at io.requery.android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:4)
07-04 11:10:04.111 28819  2982 E ACRA    : 	at io.requery.android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:5)
07-04 11:10:04.111 28819  2982 E ACRA    : 	at io.requery.android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:4)
07-04 11:10:04.111 28819  2982 E ACRA    : 	at io.requery.android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:2)
07-04 11:10:04.111 28819  2982 E ACRA    : 	at com.pushtorefresh.storio.sqlite.operations.get.PreparedGetListOfObjects.executeAsBlocking(PreparedGetListOfObjects.java:9)
07-04 11:10:04.111 28819  2982 E ACRA    : 	... 8 more
07-04 11:10:05.599 30954 30954 E e.tachiyomi.j2: Not starting debugger since process cannot load the jdwp agent.
07-04 11:10:06.085 30954  5097 E SQLiteLog: (284) automatic index on C(manga_id)
07-04 11:10:06.085 30954  5097 E SQLiteLog: (284) automatic index on R(manga_id)
07-04 11:10:06.085 30954  5097 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
07-04 11:10:06.223  5104  5104 E hiyomi.j2k:acr: Not starting debugger since process cannot load the jdwp agent.
07-04 11:10:10.068 30954  5093 E SQLiteLog: (284) automatic index on mangas(_id)
07-04 11:13:43.393 30956 30956 E e.tachiyomi.j2: Not starting debugger since process cannot load the jdwp agent.
07-04 11:13:43.798 30956  5468 E SQLiteLog: (284) automatic index on C(manga_id)
07-04 11:13:43.798 30956  5468 E SQLiteLog: (284) automatic index on R(manga_id)
07-04 11:13:43.799 30956  5468 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)

### TachiyomiJ2K version

1.5.4

### Android version

Android 12

### Device

Redmi Note 10 pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Tachiyomi](https://github.com/tachiyomiorg/tachiyomi)
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.5.4](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have updated all installed extensions.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by Jays2Kings** [comment]
I can't reproduce this with the backup provided.
Likely with your phone and a large backup, your device is probably killing the restore process. You can try this guide to see if it helps https://dontkillmyapp.com/xiaomi
