### ISSUE TITLE
Crash manga details

### ISSUE THREAD

**Issue by e-shl** [Jays2Kings/tachiyomiJ2K#1407]
### Steps to reproduce

1. Start app
2. Open Manga

### Expected behavior

See manga details

### Actual behavior

Crash app

### Crash logs

[tachiyomi_crash_logs.txt](https://github.com/Jays2Kings/tachiyomiJ2K/files/9484271/tachiyomi_crash_logs.txt)

### TachiyomiJ2K version

1.5.9

### Android version

11

### Device

Mi9

### Other details

crashing only on russian language

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Tachiyomi](https://github.com/tachiyomiorg/tachiyomi)
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.5.9](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by PiotrKowalski** [comment]
This man is a clown looking on `Acknowledgements` but I confirm that there is a bug which crashes the app when the Manga Details are clicked.

Ver 1.5.9
Android Version 12
Device Galaxy A52s 5G

**Comment by arisudesu** [comment]
I can confirm this as well.

```
App version: 1.5.9 (standard, 13f25073c, 97, 2022-09-03T21:32Z)
Android version: 10 (SDK 29)
Android build ID: QKQ1.191215.002 test-keys
Device brand: Redmi
Device manufacturer: Xiaomi
Device name: joyeuse
Device model: Redmi Note 9 Pro
Device product name: joyeuse_global

--------- beginning of system
--------- beginning of crash
09-04 14:05:24.954 10557 10557 E AndroidRuntime: FATAL EXCEPTION: main
09-04 14:05:24.954 10557 10557 E AndroidRuntime: Process: eu.kanade.tachiyomi.j2k, PID: 10557
09-04 14:05:24.954 10557 10557 E AndroidRuntime: java.util.MissingFormatArgumentException: Format specifier '%d'
09-04 14:05:24.954 10557 10557 E AndroidRuntime: 	at java.util.Formatter.format(Formatter.java:2523)
09-04 14:05:24.954 10557 10557 E AndroidRuntime: 	at java.util.Formatter.format(Formatter.java:2459)
09-04 14:05:24.954 10557 10557 E AndroidRuntime: 	at java.lang.String.format(String.java:2911)
09-04 14:05:24.954 10557 10557 E AndroidRuntime: 	at android.content.res.Resources.getQuantityString(Resources.java:532)
09-04 14:05:24.954 10557 10557 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.manga.MangaDetailsController.onCreateOptionsMenu(MangaDetailsController.kt:10)
09-04 14:05:24.954 10557 10557 E AndroidRuntime: 	at com.bluelinelabs.conductor.Controller.createOptionsMenu(Controller.java:2)
09-04 14:05:24.954 10557 10557 E AndroidRuntime: 	at com.bluelinelabs.conductor.Router.onCreateOptionsMenu(Router.java:2)
09-04 14:05:24.954 10557 10557 E AndroidRuntime: 	at com.bluelinelabs.conductor.internal.LifecycleHandler.onCreateOptionsMenu(LifecycleHandler.java:3)
09-04 14:05:24.954 10557 10557 E AndroidRuntime: 	at android.app.Fragment.performCreateOptionsMenu(Fragment.java:2655)
09-04 14:05:24.954 10557 10557 E AndroidRuntime: 	at android.app.FragmentManagerImpl.dispatchCreateOptionsMenu(FragmentManager.java:3147)
09-04 14:05:24.954 10557 10557 E AndroidRuntime: 	at android.app.FragmentController.dispatchCreateOptionsMenu(FragmentController.java:348)
09-04 14:05:24.954 10557 10557 E AndroidRuntime: 	at android.app.Activity.onCreatePanelMenu(Activity.java:4141)
09-04 14:05:24.954 10557 10557 E AndroidRuntime: 	at androidx.activity.ComponentActivity.onCreatePanelMenu(ComponentActivity.java:1)
09-04 14:05:24.954 10557 10557 E AndroidRuntime: 	at androidx.fragment.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:1)
09-04 14:05:24.954 10557 10557 E AndroidRuntime: 	at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(Unknown Source:2)
09-04 14:05:24.954 10557 10557 E AndroidRuntime: 	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onCreatePanelMenu(AppCompatDelegateImpl.java:2)
09-04 14:05:24.954 10557 10557 E AndroidRuntime: 	at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:5)
09-04 14:05:24.954 10557 10557 E AndroidRuntime: 	at androidx.appcompat.app.ToolbarActionBar$1.run(Unknown Source:2)
09-04 14:05:24.954 10557 10557 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1031)
09-04 14:05:24.954 10557 10557 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:854)
09-04 14:05:24.954 10557 10557 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:785)
09-04 14:05:24.954 10557 10557 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1016)
09-04 14:05:24.954 10557 10557 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
09-04 14:05:24.954 10557 10557 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
09-04 14:05:24.954 10557 10557 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:224)
09-04 14:05:24.954 10557 10557 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7562)
09-04 14:05:24.954 10557 10557 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-04 14:05:24.954 10557 10557 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
09-04 14:05:24.954 10557 10557 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
09-04 14:05:29.828 10690 10690 E AndroidRuntime: FATAL EXCEPTION: main
09-04 14:05:29.828 10690 10690 E AndroidRuntime: Process: eu.kanade.tachiyomi.j2k, PID: 10690
09-04 14:05:29.828 10690 10690 E AndroidRuntime: java.util.MissingFormatArgumentException: Format specifier '%d'
09-04 14:05:29.828 10690 10690 E AndroidRuntime: 	at java.util.Formatter.format(Formatter.java:2523)
09-04 14:05:29.828 10690 10690 E AndroidRuntime: 	at java.util.Formatter.format(Formatter.java:2459)
09-04 14:05:29.828 10690 10690 E AndroidRuntime: 	at java.lang.String.format(String.java:2911)
09-04 14:05:29.828 10690 10690 E AndroidRuntime: 	at android.content.res.Resources.getQuantityString(Resources.java:532)
09-04 14:05:29.828 10690 10690 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.manga.MangaDetailsController.onCreateOptionsMenu(MangaDetailsController.kt:10)
09-04 14:05:29.828 10690 10690 E AndroidRuntime: 	at com.bluelinelabs.conductor.Controller.createOptionsMenu(Controller.java:2)
09-04 14:05:29.828 10690 10690 E AndroidRuntime: 	at com.bluelinelabs.conductor.Router.onCreateOptionsMenu(Router.java:2)
09-04 14:05:29.828 10690 10690 E AndroidRuntime: 	at com.bluelinelabs.conductor.internal.LifecycleHandler.onCreateOptionsMenu(LifecycleHandler.java:3)
09-04 14:05:29.828 10690 10690 E AndroidRuntime: 	at android.app.Fragment.performCreateOptionsMenu(Fragment.java:2655)
09-04 14:05:29.828 10690 10690 E AndroidRuntime: 	at android.app.FragmentManagerImpl.dispatchCreateOptionsMenu(FragmentManager.java:3147)
09-04 14:05:29.828 10690 10690 E AndroidRuntime: 	at android.app.FragmentController.dispatchCreateOptionsMenu(FragmentController.java:348)
09-04 14:05:29.828 10690 10690 E AndroidRuntime: 	at android.app.Activity.onCreatePanelMenu(Activity.java:4141)
09-04 14:05:29.828 10690 10690 E AndroidRuntime: 	at androidx.activity.ComponentActivity.onCreatePanelMenu(ComponentActivity.java:1)
09-04 14:05:29.828 10690 10690 E AndroidRuntime: 	at androidx.fragment.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:1)
09-04 14:05:29.828 10690 10690 E AndroidRuntime: 	at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(Unknown Source:2)
09-04 14:05:29.828 10690 10690 E AndroidRuntime: 	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onCreatePanelMenu(AppCompatDelegateImpl.java:2)
09-04 14:05:29.828 10690 10690 E AndroidRuntime: 	at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:5)
09-04 14:05:29.828 10690 10690 E AndroidRuntime: 	at androidx.appcompat.app.ToolbarActionBar$1.run(Unknown Source:2)
09-04 14:05:29.828 10690 10690 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1031)
09-04 14:05:29.828 10690 10690 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:854)
09-04 14:05:29.828 10690 10690 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:785)
09-04 14:05:29.828 10690 10690 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1016)
09-04 14:05:29.828 10690 10690 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
09-04 14:05:29.828 10690 10690 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
09-04 14:05:29.828 10690 10690 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:224)
09-04 14:05:29.828 10690 10690 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7562)
09-04 14:05:29.828 10690 10690 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-04 14:05:29.828 10690 10690 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
09-04 14:05:29.828 10690 10690 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
09-04 14:05:37.957 11074 11074 E AndroidRuntime: FATAL EXCEPTION: main
09-04 14:05:37.957 11074 11074 E AndroidRuntime: Process: eu.kanade.tachiyomi.j2k, PID: 11074
09-04 14:05:37.957 11074 11074 E AndroidRuntime: java.util.MissingFormatArgumentException: Format specifier '%d'
09-04 14:05:37.957 11074 11074 E AndroidRuntime: 	at java.util.Formatter.format(Formatter.java:2523)
09-04 14:05:37.957 11074 11074 E AndroidRuntime: 	at java.util.Formatter.format(Formatter.java:2459)
09-04 14:05:37.957 11074 11074 E AndroidRuntime: 	at java.lang.String.format(String.java:2911)
09-04 14:05:37.957 11074 11074 E AndroidRuntime: 	at android.content.res.Resources.getQuantityString(Resources.java:532)
09-04 14:05:37.957 11074 11074 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.manga.MangaDetailsController.onCreateOptionsMenu(MangaDetailsController.kt:10)
09-04 14:05:37.957 11074 11074 E AndroidRuntime: 	at com.bluelinelabs.conductor.Controller.createOptionsMenu(Controller.java:2)
09-04 14:05:37.957 11074 11074 E AndroidRuntime: 	at com.bluelinelabs.conductor.Router.onCreateOptionsMenu(Router.java:2)
09-04 14:05:37.957 11074 11074 E AndroidRuntime: 	at com.bluelinelabs.conductor.internal.LifecycleHandler.onCreateOptionsMenu(LifecycleHandler.java:3)
09-04 14:05:37.957 11074 11074 E AndroidRuntime: 	at android.app.Fragment.performCreateOptionsMenu(Fragment.java:2655)
09-04 14:05:37.957 11074 11074 E AndroidRuntime: 	at android.app.FragmentManagerImpl.dispatchCreateOptionsMenu(FragmentManager.java:3147)
09-04 14:05:37.957 11074 11074 E AndroidRuntime: 	at android.app.FragmentController.dispatchCreateOptionsMenu(FragmentController.java:348)
09-04 14:05:37.957 11074 11074 E AndroidRuntime: 	at android.app.Activity.onCreatePanelMenu(Activity.java:4141)
09-04 14:05:37.957 11074 11074 E AndroidRuntime: 	at androidx.activity.ComponentActivity.onCreatePanelMenu(ComponentActivity.java:1)
09-04 14:05:37.957 11074 11074 E AndroidRuntime: 	at androidx.fragment.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:1)
09-04 14:05:37.957 11074 11074 E AndroidRuntime: 	at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(Unknown Source:2)
09-04 14:05:37.957 11074 11074 E AndroidRuntime: 	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onCreatePanelMenu(AppCompatDelegateImpl.java:2)
09-04 14:05:37.957 11074 11074 E AndroidRuntime: 	at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:5)
09-04 14:05:37.957 11074 11074 E AndroidRuntime: 	at androidx.appcompat.app.ToolbarActionBar$1.run(Unknown Source:2)
09-04 14:05:37.957 11074 11074 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1031)
09-04 14:05:37.957 11074 11074 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:854)
09-04 14:05:37.957 11074 11074 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:785)
09-04 14:05:37.957 11074 11074 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1016)
09-04 14:05:37.957 11074 11074 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
09-04 14:05:37.957 11074 11074 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
09-04 14:05:37.957 11074 11074 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:224)
09-04 14:05:37.957 11074 11074 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7562)
09-04 14:05:37.957 11074 11074 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-04 14:05:37.957 11074 11074 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
09-04 14:05:37.957 11074 11074 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
09-04 14:05:59.752 11367 11367 E AndroidRuntime: FATAL EXCEPTION: main
09-04 14:05:59.752 11367 11367 E AndroidRuntime: Process: eu.kanade.tachiyomi.j2k, PID: 11367
09-04 14:05:59.752 11367 11367 E AndroidRuntime: java.util.MissingFormatArgumentException: Format specifier '%d'
09-04 14:05:59.752 11367 11367 E AndroidRuntime: 	at java.util.Formatter.format(Formatter.java:2523)
09-04 14:05:59.752 11367 11367 E AndroidRuntime: 	at java.util.Formatter.format(Formatter.java:2459)
09-04 14:05:59.752 11367 11367 E AndroidRuntime: 	at java.lang.String.format(String.java:2911)
09-04 14:05:59.752 11367 11367 E AndroidRuntime: 	at android.content.res.Resources.getQuantityString(Resources.java:532)
09-04 14:05:59.752 11367 11367 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.manga.MangaDetailsController.onCreateOptionsMenu(MangaDetailsController.kt:10)
09-04 14:05:59.752 11367 11367 E AndroidRuntime: 	at com.bluelinelabs.conductor.Controller.createOptionsMenu(Controller.java:2)
09-04 14:05:59.752 11367 11367 E AndroidRuntime: 	at com.bluelinelabs.conductor.Router.onCreateOptionsMenu(Router.java:2)
09-04 14:05:59.752 11367 11367 E AndroidRuntime: 	at com.bluelinelabs.conductor.internal.LifecycleHandler.onCreateOptionsMenu(LifecycleHandler.java:3)
09-04 14:05:59.752 11367 11367 E AndroidRuntime: 	at android.app.Fragment.performCreateOptionsMenu(Fragment.java:2655)
09-04 14:05:59.752 11367 11367 E AndroidRuntime: 	at android.app.FragmentManagerImpl.dispatchCreateOptionsMenu(FragmentManager.java:3147)
09-04 14:05:59.752 11367 11367 E AndroidRuntime: 	at android.app.FragmentController.dispatchCreateOptionsMenu(FragmentController.java:348)
09-04 14:05:59.752 11367 11367 E AndroidRuntime: 	at android.app.Activity.onCreatePanelMenu(Activity.java:4141)
09-04 14:05:59.752 11367 11367 E AndroidRuntime: 	at androidx.activity.ComponentActivity.onCreatePanelMenu(ComponentActivity.java:1)
09-04 14:05:59.752 11367 11367 E AndroidRuntime: 	at androidx.fragment.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:1)
09-04 14:05:59.752 11367 11367 E AndroidRuntime: 	at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(Unknown Source:2)
09-04 14:05:59.752 11367 11367 E AndroidRuntime: 	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onCreatePanelMenu(AppCompatDelegateImpl.java:2)
09-04 14:05:59.752 11367 11367 E AndroidRuntime: 	at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:5)
09-04 14:05:59.752 11367 11367 E AndroidRuntime: 	at androidx.appcompat.app.ToolbarActionBar$1.run(Unknown Source:2)
09-04 14:05:59.752 11367 11367 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1031)
09-04 14:05:59.752 11367 11367 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:854)
09-04 14:05:59.752 11367 11367 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:785)
09-04 14:05:59.752 11367 11367 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1016)
09-04 14:05:59.752 11367 11367 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
09-04 14:05:59.752 11367 11367 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
09-04 14:05:59.752 11367 11367 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:224)
09-04 14:05:59.752 11367 11367 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7562)
09-04 14:05:59.752 11367 11367 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-04 14:05:59.752 11367 11367 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
09-04 14:05:59.752 11367 11367 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
09-04 14:09:22.855 11486 11486 E AndroidRuntime: FATAL EXCEPTION: main
09-04 14:09:22.855 11486 11486 E AndroidRuntime: Process: eu.kanade.tachiyomi.j2k, PID: 11486
09-04 14:09:22.855 11486 11486 E AndroidRuntime: java.util.MissingFormatArgumentException: Format specifier '%d'
09-04 14:09:22.855 11486 11486 E AndroidRuntime: 	at java.util.Formatter.format(Formatter.java:2523)
09-04 14:09:22.855 11486 11486 E AndroidRuntime: 	at java.util.Formatter.format(Formatter.java:2459)
09-04 14:09:22.855 11486 11486 E AndroidRuntime: 	at java.lang.String.format(String.java:2911)
09-04 14:09:22.855 11486 11486 E AndroidRuntime: 	at android.content.res.Resources.getQuantityString(Resources.java:532)
09-04 14:09:22.855 11486 11486 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.manga.MangaDetailsController.onCreateOptionsMenu(MangaDetailsController.kt:10)
09-04 14:09:22.855 11486 11486 E AndroidRuntime: 	at com.bluelinelabs.conductor.Controller.createOptionsMenu(Controller.java:2)
09-04 14:09:22.855 11486 11486 E AndroidRuntime: 	at com.bluelinelabs.conductor.Router.onCreateOptionsMenu(Router.java:2)
09-04 14:09:22.855 11486 11486 E AndroidRuntime: 	at com.bluelinelabs.conductor.internal.LifecycleHandler.onCreateOptionsMenu(LifecycleHandler.java:3)
09-04 14:09:22.855 11486 11486 E AndroidRuntime: 	at android.app.Fragment.performCreateOptionsMenu(Fragment.java:2655)
09-04 14:09:22.855 11486 11486 E AndroidRuntime: 	at android.app.FragmentManagerImpl.dispatchCreateOptionsMenu(FragmentManager.java:3147)
09-04 14:09:22.855 11486 11486 E AndroidRuntime: 	at android.app.FragmentController.dispatchCreateOptionsMenu(FragmentController.java:348)
09-04 14:09:22.855 11486 11486 E AndroidRuntime: 	at android.app.Activity.onCreatePanelMenu(Activity.java:4141)
09-04 14:09:22.855 11486 11486 E AndroidRuntime: 	at androidx.activity.ComponentActivity.onCreatePanelMenu(ComponentActivity.java:1)
09-04 14:09:22.855 11486 11486 E AndroidRuntime: 	at androidx.fragment.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:1)
09-04 14:09:22.855 11486 11486 E AndroidRuntime: 	at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(Unknown Source:2)
09-04 14:09:22.855 11486 11486 E AndroidRuntime: 	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onCreatePanelMenu(AppCompatDelegateImpl.java:2)
09-04 14:09:22.855 11486 11486 E AndroidRuntime: 	at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:5)
09-04 14:09:22.855 11486 11486 E AndroidRuntime: 	at androidx.appcompat.app.ToolbarActionBar$1.run(Unknown Source:2)
09-04 14:09:22.855 11486 11486 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1031)
09-04 14:09:22.855 11486 11486 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:854)
09-04 14:09:22.855 11486 11486 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:785)
09-04 14:09:22.855 11486 11486 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1016)
09-04 14:09:22.855 11486 11486 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
09-04 14:09:22.855 11486 11486 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
09-04 14:09:22.855 11486 11486 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:224)
09-04 14:09:22.855 11486 11486 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7562)
09-04 14:09:22.855 11486 11486 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-04 14:09:22.855 11486 11486 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
09-04 14:09:22.855 11486 11486 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
--------- beginning of main
09-04 14:10:01.016 12408 12408 E e.tachiyomi.j2: Not starting debugger since process cannot load the jdwp agent.
09-04 14:10:01.158 12408 12408 E libc    : Access denied finding property "ro.vendor.df.effect.conflict"
09-04 14:10:01.823 12408 12463 E SQLiteLog: (284) automatic index on C(manga_id)
09-04 14:10:01.823 12408 12463 E SQLiteLog: (284) automatic index on R(manga_id)
09-04 14:10:01.823 12408 12463 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
09-04 14:10:10.873 12408 12501 E SQLiteLog: (284) automatic index on mangas(_id)

```

**Comment by nzoba** [comment]
This is caused by a wrong translation format in [russian](https://hosted.weblate.org/translate/tachiyomi/tachiyomi-j2k/ru/?checksum=425960f58a1e7447). It's the same in [polish](https://hosted.weblate.org/translate/tachiyomi/tachiyomi-j2k/pl/?checksum=425960f58a1e7447). This has been fixed and will be available in the next release

**Comment by e-shl** [comment]
APKs has been re-uploaded
