### ISSUE TITLE
Jumping back pages using volume keys while reading

### ISSUE THREAD

**Issue by LunchBox33** [Jays2Kings/tachiyomiJ2K#1534]
### Steps to reproduce

1. Read any series downloaded on SD
2. Turn pages with audio buttons

### Expected behavior

It should work normally without brining me back pages

### Actual behavior

Jumps back pages. Example : arriving at page 16/32 once button pressed to next page it jump back to page 3or 6/32.

### Crash logs
App version: 1.6.4 (standard, 2080add1b, 102, 2023-03-16T16:59Z)
Android version: 11 (SDK 30)
Android build ID: 2022-11-22_10-20_3.3.1_e4f27d41a
Device brand: Onyx
Device manufacturer: ONYX
Device name: Leaf2
Device model: Leaf2
Device product name: Leaf2

--------- beginning of system
--------- beginning of main
03-29 11:28:22.648 11193 11227 E FrameEvents: updateAcquireFence: Did not find frame.
03-29 11:41:45.185 11193 11227 E FrameEvents: updateAcquireFence: Did not find frame.
03-29 11:42:25.585 11193 11227 E FrameEvents: updateAcquireFence: Did not find frame.
03-29 14:49:23.826 11193 11227 E FrameEvents: updateAcquireFence: Did not find frame.
03-29 14:49:56.357 11193 11227 E FrameEvents: updateAcquireFence: Did not find frame.
03-29 14:50:19.353 11193 11227 E FrameEvents: updateAcquireFence: Did not find frame.
03-29 14:56:09.557 11193 11227 E FrameEvents: updateAcquireFence: Did not find frame.
03-29 14:57:51.949 11193 11227 E FrameEvents: updateAcquireFence: Did not find frame.
03-29 15:01:33.904 11193 11227 E FrameEvents: updateAcquireFence: Did not find frame.
03-29 15:04:02.963 17557 17557 E e.tachiyomi.j2: Not starting debugger since process cannot load the jdwp agent.
03-29 15:04:03.989 17557 17588 E ChimeraModuleLdr: Failed to load code for module FileApk(/data/user_de/0/com.google.android.gms/app_chimera/m/00000054/MeasurementDynamite.apk)
03-29 15:04:03.989 17557 17588 E ChimeraModuleLdr: guc: Can't load code for MeasurementDynamite.apk
03-29 15:04:03.989 17557 17588 E ChimeraModuleLdr: 	at goe.f(:com.google.android.gms@231015037@23.10.15 (150400-517566699):8)
03-29 15:04:03.989 17557 17588 E ChimeraModuleLdr: 	at gtz.a(:com.google.android.gms@231015037@23.10.15 (150400-517566699):45)
03-29 15:04:03.989 17557 17588 E ChimeraModuleLdr: 	at gtz.b(:com.google.android.gms@231015037@23.10.15 (150400-517566699):4)
03-29 15:04:03.989 17557 17588 E ChimeraModuleLdr: 	at com.google.android.gms.dynamiteloader.DynamiteLoaderV2.loadModule2NoCrashUtils(:com.google.android.gms@231015037@23.10.15 (150400-517566699):50)
03-29 15:04:03.989 17557 17588 E ChimeraModuleLdr: 	at com.google.android.gms.chimera.container.DynamiteLoaderImpl.loadModule(:com.google.android.gms@231015037@23.10.15 (150400-517566699):4)
03-29 15:04:03.989 17557 17588 E ChimeraModuleLdr: 	at com.google.android.gms.chimera.container.DynamiteLoaderImpl.createModuleContext3NoCrashUtils(:com.google.android.gms@231015037@23.10.15 (150400-517566699):7)
03-29 15:04:03.989 17557 17588 E ChimeraModuleLdr: 	at afnk.en(:com.google.android.gms@231015037@23.10.15 (150400-517566699):5)
03-29 15:04:03.989 17557 17588 E ChimeraModuleLdr: 	at ghu.onTransact(:com.google.android.gms@231015037@23.10.15 (150400-517566699):12)
03-29 15:04:03.989 17557 17588 E ChimeraModuleLdr: 	at android.os.Binder.transact(Binder.java:1043)
03-29 15:04:03.989 17557 17588 E ChimeraModuleLdr: 	at com.google.android.gms.internal.common.zza.zzB(com.google.android.gms:play-services-basement@@18.0.0:8)
03-29 15:04:03.989 17557 17588 E ChimeraModuleLdr: 	at com.google.android.gms.dynamite.zzq.zzi(com.google.android.gms:play-services-basement@@18.0.0:19)
03-29 15:04:03.989 17557 17588 E ChimeraModuleLdr: 	at com.google.android.gms.dynamite.DynamiteModule.load(com.google.android.gms:play-services-basement@@18.0.0:428)
03-29 15:04:03.989 17557 17588 E ChimeraModuleLdr: 	at com.google.android.gms.internal.measurement.zzee.zzf(com.google.android.gms:play-services-measurement-sdk-api@@21.1.0:5)
03-29 15:04:03.989 17557 17588 E ChimeraModuleLdr: 	at com.google.android.gms.internal.measurement.zzcx.zza(com.google.android.gms:play-services-measurement-sdk-api@@21.1.0:17)
03-29 15:04:03.989 17557 17588 E ChimeraModuleLdr: 	at com.google.android.gms.internal.measurement.zzdt.run(com.google.android.gms:play-services-measurement-sdk-api@@21.1.0:13)
03-29 15:04:03.989 17557 17588 E ChimeraModuleLdr: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
03-29 15:04:03.989 17557 17588 E ChimeraModuleLdr: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
03-29 15:04:03.989 17557 17588 E ChimeraModuleLdr: 	at java.lang.Thread.run(Thread.java:923)
03-29 15:04:03.994 17557 17588 E DynamiteLoaderV2Impl: Failed to create module context.
03-29 15:04:03.994 17557 17588 E DynamiteLoaderV2Impl: guc: Can't load code for MeasurementDynamite.apk
03-29 15:04:03.994 17557 17588 E DynamiteLoaderV2Impl: 	at goe.f(:com.google.android.gms@231015037@23.10.15 (150400-517566699):8)
03-29 15:04:03.994 17557 17588 E DynamiteLoaderV2Impl: 	at gtz.a(:com.google.android.gms@231015037@23.10.15 (150400-517566699):45)
03-29 15:04:03.994 17557 17588 E DynamiteLoaderV2Impl: 	at gtz.b(:com.google.android.gms@231015037@23.10.15 (150400-517566699):4)
03-29 15:04:03.994 17557 17588 E DynamiteLoaderV2Impl: 	at com.google.android.gms.dynamiteloader.DynamiteLoaderV2.loadModule2NoCrashUtils(:com.google.android.gms@231015037@23.10.15 (150400-517566699):50)
03-29 15:04:03.994 17557 17588 E DynamiteLoaderV2Impl: 	at com.google.android.gms.chimera.container.DynamiteLoaderImpl.loadModule(:com.google.android.gms@231015037@23.10.15 (150400-517566699):4)
03-29 15:04:03.994 17557 17588 E DynamiteLoaderV2Impl: 	at com.google.android.gms.chimera.container.DynamiteLoaderImpl.createModuleContext3NoCrashUtils(:com.google.android.gms@231015037@23.10.15 (150400-517566699):7)
03-29 15:04:03.994 17557 17588 E DynamiteLoaderV2Impl: 	at afnk.en(:com.google.android.gms@231015037@23.10.15 (150400-517566699):5)
03-29 15:04:03.994 17557 17588 E DynamiteLoaderV2Impl: 	at ghu.onTransact(:com.google.android.gms@231015037@23.10.15 (150400-517566699):12)
03-29 15:04:03.994 17557 17588 E DynamiteLoaderV2Impl: 	at android.os.Binder.transact(Binder.java:1043)
03-29 15:04:03.994 17557 17588 E DynamiteLoaderV2Impl: 	at com.google.android.gms.internal.common.zza.zzB(com.google.android.gms:play-services-basement@@18.0.0:8)
03-29 15:04:03.994 17557 17588 E DynamiteLoaderV2Impl: 	at com.google.android.gms.dynamite.zzq.zzi(com.google.android.gms:play-services-basement@@18.0.0:19)
03-29 15:04:03.994 17557 17588 E DynamiteLoaderV2Impl: 	at com.google.android.gms.dynamite.DynamiteModule.load(com.google.android.gms:play-services-basement@@18.0.0:428)
03-29 15:04:03.994 17557 17588 E DynamiteLoaderV2Impl: 	at com.google.android.gms.internal.measurement.zzee.zzf(com.google.android.gms:play-services-measurement-sdk-api@@21.1.0:5)
03-29 15:04:03.994 17557 17588 E DynamiteLoaderV2Impl: 	at com.google.android.gms.internal.measurement.zzcx.zza(com.google.android.gms:play-services-measurement-sdk-api@@21.1.0:17)
03-29 15:04:03.994 17557 17588 E DynamiteLoaderV2Impl: 	at com.google.android.gms.internal.measurement.zzdt.run(com.google.android.gms:play-services-measurement-sdk-api@@21.1.0:13)
03-29 15:04:03.994 17557 17588 E DynamiteLoaderV2Impl: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
03-29 15:04:03.994 17557 17588 E DynamiteLoaderV2Impl: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
03-29 15:04:03.994 17557 17588 E DynamiteLoaderV2Impl: 	at java.lang.Thread.run(Thread.java:923)
03-29 15:04:05.607 17700 17700 E hiyomi.j2k:acr: Not starting debugger since process cannot load the jdwp agent.
03-29 15:04:06.576 17700 17795 E ACRA    : Failed to send crash reports for /data/user/0/eu.kanade.tachiyomi.j2k/app_ACRA-approved/2023-02-13T07:23:41.921+01:00.stacktrace
03-29 15:05:38.952 17557 17557 E SQLiteLog: (283) recovered 93 frames from WAL file /data/user/0/eu.kanade.tachiyomi.j2k/databases/tachiyomi.db-wal
03-29 15:05:38.981 17557 17693 E SQLiteLog: (284) automatic index on C(manga_id)
03-29 15:05:38.981 17557 17693 E SQLiteLog: (284) automatic index on R(manga_id)
03-29 15:05:38.981 17557 17693 E SQLiteLog: (284) automatic index on B(manga_id)
03-29 15:05:38.981 17557 17693 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
03-29 15:05:39.083 17557 17691 E SQLiteLog: (284) automatic index on C(manga_id)
03-29 15:05:39.084 17557 17691 E SQLiteLog: (284) automatic index on mangas(_id)

### TachiyomiJ2K version

1.6.4

### Android version

Android 11

### Device

Boox Leaf 2

### Other details

This happens on most series not on every single one.
Doesn't matter the number of pages or on which extension it was downloaded from

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Tachiyomi](https://github.com/tachiyomiorg/tachiyomi)
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.6.4](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have updated all installed extensions.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by Jays2Kings** [comment]
While I'd normally clown on you for making a duplicate issue to the issue(s) _made literally right before this one_, since you actually used the template yours gets to stay
