### ISSUE TITLE
Application crashes upon restoration of backup

### ISSUE THREAD

**Issue by winniesim20** [Jays2Kings/tachiyomiJ2K#1780]
### Steps to reproduce

1. Download and install TachiyomiJ2K 1.7.4
2. Setting >> backup and restore
3. Restore backup >> backup chosen (tachiyomi backup)
4. Back up restored with 0 errors
5. Application crashes and shuts down

### Expected behavior

Application restores and loads all backed up libraries.
Application stays open to allow for app activities.

### Actual behavior

Application crashes and shuts down without any crash logs. 

### Crash logs

No crash log provided. Application closes itself. 

### TachiyomiJ2K version

1.7.4

### Android version

Android 13

### Device

Google apixel 4a

### Other details

Back up chosen for restoration was from main version of Tachiyomi

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Tachiyomi](https://github.com/tachiyomiorg/tachiyomi)
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.7.4](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have updated all installed extensions.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by ImpenetrableNoble** [comment]
As much as this report as really tempting for him to fix it he wouldn't at all which is hopeless because he won't, just fork it and start learning your own programming language to fix it yourself, don't report it anymore.

**Comment by DukeSinclair** [comment]
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
	at android.app.SharedPreferencesImpl.getInt(SharedPreferencesImpl.java:321)
	at com.fredporciuncula.flow.preferences.IntPreference.get(SourceFile:15)
	at eu.kanade.tachiyomi.ui.extension.ExtensionAdapter.<init>(Unknown Source:48)
	at eu.kanade.tachiyomi.ui.extension.ExtensionBottomSheet.onCreate(Unknown Source:12)
	at eu.kanade.tachiyomi.ui.source.BrowseController.onViewCreated(SourceFile:181)
	at eu.kanade.tachiyomi.ui.base.controller.BaseController$1.postCreateView(Unknown Source:12)
	at com.bluelinelabs.conductor.Controller.inflate(SourceFile:115)
	at com.bluelinelabs.conductor.ControllerChangeHandler.executeChange(SourceFile:186)
	at com.bluelinelabs.conductor.Router.performControllerChange(SourceFile:2)
	at com.bluelinelabs.conductor.Router.setBackstack(SourceFile:483)
	at eu.kanade.tachiyomi.ui.main.MainActivity$$ExternalSyntheticLambda6.onNavigationItemSelected(SourceFile:167)
	at com.google.android.material.navigation.NavigationBarView$1.onMenuItemSelected(Unknown Source:45)
	at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(Unknown Source:4)
	at androidx.appcompat.view.menu.MenuItemImpl.invoke(SourceFile:15)
	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(Unknown Source:13)
	at com.google.android.material.navigation.NavigationBarMenuView$1.onClick(Unknown Source:19)
	at android.view.View.performClick(View.java:7571)
	at android.view.View.performClickInternal(View.java:7548)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:29771)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8442)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:560)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)

**Comment by dobbleg1000** [comment]
Getting this same error. If we need help troubleshooting

**Comment by dobbleg1000** [comment]
@DukeSinclair 
Ik its been a bit since your post. Making a new backup not including SETTINGS seemed to let me restore successfully.
