### ISSUE TITLE
App crash when turn to some page

### ISSUE THREAD

**Issue by zanjie1999** [Jays2Kings/tachiyomiJ2K#1834]
### Steps to reproduce

Open a specific book and turn the pages
For example 动漫之家  《我才不想当女孩子！》  第8.5话 page 3

### Expected behavior

Flip Page and nothong

### Actual behavior

Flip Page and app crash

### Crash logs

adb logcat
```
10-11 23:28:35.004  6360  6360 I zygote  : Deoptimizing java.lang.Appendable kotlin.collections.CollectionsKt___CollectionsKt.joinTo(java.lang.Iterable, java.lang.Appendable, java.lang.CharSequence, java.lang.CharSequence, java.lang.CharSequence, int, java.lang.CharSequence, kotlin.jvm.functions.Function1) due to JIT inline cache
10-11 23:28:35.006  6360  6360 I zygote  : Deoptimizing int kotlin.text.StringsKt__StringsKt.getLastIndex(java.lang.CharSequence) due to JIT inline cache
10-11 23:28:35.010  6360  6360 I zygote  : Deoptimizing void androidx.emoji2.viewsintegration.EmojiTextViewHelper$HelperInternal19.setEnabled(boolean) due to JIT inline cache
10-11 23:28:35.024  6360  6360 I zygote  : Deoptimizing void androidx.appcompat.widget.AppCompatImageHelper.loadFromAttributes(android.util.AttributeSet, int) due to JIT inline cache
10-11 23:28:35.025  6360  6360 I zygote  : Deoptimizing android.content.res.ColorStateList androidx.appcompat.widget.TintTypedArray.getColorStateList(int) due to JIT inline cache
10-11 23:28:35.035  6360  6360 I zygote  : Deoptimizing void androidx.constraintlayout.widget.ConstraintLayout.init(android.util.AttributeSet, int) due to JIT inline cache
10-11 23:28:35.044  6360  6360 I zygote  : Deoptimizing void androidx.appcompat.widget.AppCompatImageHelper.applySupportImageTint() due to JIT inline cache
10-11 23:28:35.045  6360  6360 I zygote  : Deoptimizing void androidx.appcompat.widget.AppCompatImageHelper.applyImageLevel() due to JIT inline cache
10-11 23:28:35.207  6360  6441 I zygote  : Deoptimizing java.util.List kotlin.sequences.SequencesKt___SequencesKt.toList(kotlin.sequences.Sequence) due to JIT inline cache
10-11 23:28:35.259  6360  6441 I zygote  : Deoptimizing void kotlinx.coroutines.DispatchedTask.run() due to class hierarchy analysis
10-11 23:28:35.523  6360  6360 I zygote  : Deoptimizing void androidx.appcompat.widget.AppCompatImageView.drawableStateChanged() due to JIT inline cache
10-11 23:28:35.549  6360  6360 I zygote  : Deoptimizing kotlinx.coroutines.DisposableHandle kotlinx.coroutines.JobSupport.invokeOnCompletion(boolean, boolean, kotlin.jvm.functions.Function1) due to JIT inline cache
10-11 23:28:35.564  6360  6442 I zygote  : Deoptimizing int eu.kanade.tachiyomi.source.LocalSource$$ExternalSyntheticLambda0.compare(java.lang.Object, java.lang.Object) due to JIT inline cache
10-11 23:28:35.620  6360  6441 D skia    : JPEG Decode 35
10-11 23:28:35.628  6360  6423 D GRALLOC-ROCKCHIP: leave, w : 270, h : 360, format : 0x1,internal_format : 0x1, usage : 0x100. size=391680,pixel_stride=272,byte_stride=1088
10-11 23:28:35.628  6360  6423 D GRALLOC-ROCKCHIP: leave: prime_fd=123,share_attr_fd=124
10-11 23:28:35.746  6360  6360 I zygote  : Deoptimizing void androidx.constraintlayout.widget.ConstraintLayout.onMeasure(int, int) due to JIT inline cache
10-11 23:28:35.747  6360  6360 I zygote  : Deoptimizing void androidx.constraintlayout.widget.ConstraintLayout.resolveSystem(androidx.constraintlayout.core.widgets.ConstraintWidgetContainer, int, int, int) due to JIT inline cache
10-11 23:28:35.749  6360  6360 I zygote  : Deoptimizing void androidx.constraintlayout.widget.ConstraintLayout$Measurer.didMeasures() due to JIT inline cache
10-11 23:28:35.879  6360  6423 D mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
10-11 23:28:36.021  6360  6360 I zygote  : Deoptimizing void androidx.constraintlayout.widget.ConstraintLayout.onLayout(boolean, int, int, int, int) due to JIT inline cache
10-11 23:28:36.052  6360  6360 E jeffy   : applyEinkMode :eu.kanade.tachiyomi.j2k/eu.kanade.tachiyomi.ui.main.MainActivity, dirty:Rect(0, 0 - 1404, 1872)
10-11 23:28:36.066  6360  6378 I zygote  : Deoptimizing java.lang.Object com.google.android.gms.measurement.internal.zzdt.zza(java.lang.Object) due to JIT inline cache
10-11 23:28:36.080  6360  6360 I zygote  : Deoptimizing kotlinx.coroutines.internal.LockFreeLinkedListNode kotlinx.coroutines.internal.LockFreeLinkedListNode.correctPrev() due to JIT inline cache
10-11 23:28:36.112  6360  6360 I zygote  : Deoptimizing boolean kotlinx.coroutines.JobSupport.isActive() due to JIT inline cache
10-11 23:28:36.153  6360  6396 D OpenGLRenderer: Bitmap.cpp allocateHeapBitmap addr = ccb83700
10-11 23:28:36.170  6360  6396 D OpenGLRenderer: Bitmap.cpp allocateHeapBitmap addr = ccaa4440
10-11 23:28:36.195  6360  6423 D GRALLOC-ROCKCHIP: leave, w : 270, h : 270, format : 0x1,internal_format : 0x1, usage : 0x100. size=293760,pixel_stride=272,byte_stride=1088
10-11 23:28:36.195  6360  6423 D GRALLOC-ROCKCHIP: leave: prime_fd=126,share_attr_fd=127
10-11 23:28:36.366  6360  6360 I zygote  : Deoptimizing kotlinx.coroutines.DisposableHandle kotlinx.coroutines.JobSupport.invokeOnCompletion(boolean, boolean, kotlin.jvm.functions.Function1) due to JIT inline cache
10-11 23:28:36.389  6360  6360 D ViewRootImpl[ReaderActivity]: changeCanvasOpacity: opaque=true
10-11 23:28:36.478  6360  6360 E jeffy   : applyEinkMode :eu.kanade.tachiyomi.j2k/eu.kanade.tachiyomi.ui.reader.ReaderActivity, dirty:Rect(0, 0 - 1404, 1872)
10-11 23:28:36.505  6360  6396 D skia    : JPEG Decode 99
10-11 23:28:36.524  6360  6423 D GRALLOC-ROCKCHIP: leave, w : 1872, h : 1404, format : 0x1,internal_format : 0x1, usage : 0xb00. size=10513152,pixel_stride=1872,byte_stride=7488
10-11 23:28:36.524  6360  6423 D GRALLOC-ROCKCHIP: leave: prime_fd=133,share_attr_fd=134
10-11 23:28:36.526  6360  6423 D OpenGLRenderer: Bitmap.cpp allocateHeapBitmap addr = ccb08d00
10-11 23:28:36.552  6360  6423 D GRALLOC-ROCKCHIP: leave, w : 720, h : 960, format : 0x1,internal_format : 0x1, usage : 0x100. size=2764800,pixel_stride=720,byte_stride=2880
10-11 23:28:36.552  6360  6423 D GRALLOC-ROCKCHIP: leave: prime_fd=131,share_attr_fd=132
10-11 23:28:36.620  6360  6360 I zygote  : Deoptimizing android.view.View androidx.recyclerview.widget.ChildHelper.getUnfilteredChildAt(int) due to JIT inline cache
10-11 23:28:36.660  6360  6360 W StaticLayout: maxLineHeight should not be -1.  maxLines:2 lineCount:2
10-11 23:28:36.670  6360  6360 I chatty  : uid=10038(eu.kanade.tachiyomi.j2k) identical 1 line
10-11 23:28:36.674  6360  6360 W StaticLayout: maxLineHeight should not be -1.  maxLines:2 lineCount:2
10-11 23:28:36.871  6360  6360 E jeffy   : applyEinkMode :eu.kanade.tachiyomi.j2k/eu.kanade.tachiyomi.ui.main.MainActivity, dirty:Rect(0, 0 - 1404, 1872)
10-11 23:28:36.875  6360  6371 I zygote  : NativeAlloc concurrent copying GC freed 65178(4MB) AllocSpace objects, 146(2MB) LOS objects, 32% free, 12MB/18MB, paused 851us total 264.888ms
10-11 23:28:36.896  6360  6369 E System  : Uncaught exception thrown by finalizer
10-11 23:28:36.905  6360  6369 E System  : java.lang.NullPointerException: Attempt to invoke virtual method 'void dalvik.system.CloseGuard.close()' on a null object reference
10-11 23:28:36.905  6360  6369 E System  :      at java.util.zip.ZipFile.close(ZipFile.java:639)
10-11 23:28:36.905  6360  6369 E System  :      at java.util.zip.ZipFile.finalize(ZipFile.java:699)
10-11 23:28:36.905  6360  6369 E System  :      at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:250)
10-11 23:28:36.905  6360  6369 E System  :      at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:237)
10-11 23:28:36.905  6360  6369 E System  :      at java.lang.Daemons$Daemon.run(Daemons.java:103)
10-11 23:28:36.905  6360  6369 E System  :      at java.lang.Thread.run(Thread.java:764)
10-11 23:28:36.906  6360  6369 E System  : Uncaught exception thrown by finalizer
10-11 23:28:36.907  6360  6369 E System  : java.lang.NullPointerException: Attempt to invoke virtual method 'void dalvik.system.CloseGuard.close()' on a null object reference
10-11 23:28:36.907  6360  6369 E System  :      at java.util.zip.ZipFile.close(ZipFile.java:639)
10-11 23:28:36.907  6360  6369 E System  :      at java.util.zip.ZipFile.finalize(ZipFile.java:699)
10-11 23:28:36.907  6360  6369 E System  :      at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:250)
10-11 23:28:36.907  6360  6369 E System  :      at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:237)
10-11 23:28:36.907  6360  6369 E System  :      at java.lang.Daemons$Daemon.run(Daemons.java:103)
10-11 23:28:36.907  6360  6369 E System  :      at java.lang.Thread.run(Thread.java:764)
10-11 23:28:36.907  6360  6369 E System  : Uncaught exception thrown by finalizer
10-11 23:28:36.907  6360  6369 E System  : java.lang.NullPointerException: Attempt to invoke virtual method 'void dalvik.system.CloseGuard.close()' on a null object reference
10-11 23:28:36.907  6360  6369 E System  :      at java.util.zip.ZipFile.close(ZipFile.java:639)
10-11 23:28:36.907  6360  6369 E System  :      at java.util.zip.ZipFile.finalize(ZipFile.java:699)
10-11 23:28:36.907  6360  6369 E System  :      at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:250)
10-11 23:28:36.907  6360  6369 E System  :      at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:237)
10-11 23:28:36.907  6360  6369 E System  :      at java.lang.Daemons$Daemon.run(Daemons.java:103)
10-11 23:28:36.907  6360  6369 E System  :      at java.lang.Thread.run(Thread.java:764)
10-11 23:28:36.970  6360  6360 E jeffy   : applyEinkMode :eu.kanade.tachiyomi.j2k/eu.kanade.tachiyomi.ui.reader.ReaderActivity, dirty:Rect(0, 0 - 1404, 1872)
10-11 23:28:36.994  6360  6360 I zygote  : Deoptimizing kotlin.coroutines.CoroutineContext kotlinx.coroutines.CoroutineContextKt.foldCopies(kotlin.coroutines.CoroutineContext, kotlin.coroutines.CoroutineContext, boolean) due to JIT inline cache
10-11 23:28:37.027  6360  6423 D GRALLOC-ROCKCHIP: leave, w : 1872, h : 1404, format : 0x1,internal_format : 0x1, usage : 0xb00. size=10513152,pixel_stride=1872,byte_stride=7488
10-11 23:28:37.027  6360  6423 D GRALLOC-ROCKCHIP: leave: prime_fd=138,share_attr_fd=139
10-11 23:28:37.089  6360  6396 D OpenGLRenderer: Bitmap.cpp allocateHeapBitmap addr = cc580000
10-11 23:28:37.117  6360  6396 D OpenGLRenderer: Bitmap.cpp allocateHeapBitmap addr = cbf00000
10-11 23:28:37.162  6360  6423 D GRALLOC-ROCKCHIP: leave, w : 1872, h : 1404, format : 0x1,internal_format : 0x1, usage : 0xb00. size=10513152,pixel_stride=1872,byte_stride=7488
10-11 23:28:37.162  6360  6423 D GRALLOC-ROCKCHIP: leave: prime_fd=141,share_attr_fd=142
10-11 23:28:37.190  6360  6423 D GRALLOC-ROCKCHIP: leave, w : 720, h : 720, format : 0x1,internal_format : 0x1, usage : 0x100. size=2073600,pixel_stride=720,byte_stride=2880
10-11 23:28:37.190  6360  6423 D GRALLOC-ROCKCHIP: leave: prime_fd=130,share_attr_fd=137
10-11 23:28:37.241  6360  6423 W libEGL  : EGLNativeWindowType 0xd1e1f808 disconnect failed
10-11 23:28:37.274  6360  6453 D OpenGLRenderer: Bitmap.cpp allocateHeapBitmap addr = cb600000
10-11 23:28:37.276  6360  6450 D OpenGLRenderer: Bitmap.cpp allocateHeapBitmap addr = ca400000
10-11 23:28:37.342  6360  6396 D skia    : JPEG Decode 31
10-11 23:28:37.346  6360  6423 D GRALLOC-ROCKCHIP: leave, w : 270, h : 360, format : 0x1,internal_format : 0x1, usage : 0x100. size=391680,pixel_stride=272,byte_stride=1088
10-11 23:28:37.346  6360  6423 D GRALLOC-ROCKCHIP: leave: prime_fd=92,share_attr_fd=93
10-11 23:28:37.384  6360  6423 D GRALLOC-ROCKCHIP: leave, w : 1872, h : 1404, format : 0x1,internal_format : 0x1, usage : 0xb00. size=10513152,pixel_stride=1872,byte_stride=7488
10-11 23:28:37.384  6360  6423 D GRALLOC-ROCKCHIP: leave: prime_fd=97,share_attr_fd=108
10-11 23:28:37.430  6360  6360 I zygote  : Deoptimizing int kotlin.collections.CollectionsKt__CollectionsKt.getLastIndex(java.util.List) due to JIT inline cache
10-11 23:28:37.438  6360  6396 D OpenGLRenderer: Bitmap.cpp allocateHeapBitmap addr = cc103680
10-11 23:28:37.439  6360  6396 D OpenGLRenderer: Bitmap.cpp allocateHeapBitmap addr = ccaa4e00
10-11 23:28:37.445  6360  6423 D GRALLOC-ROCKCHIP: leave, w : 270, h : 270, format : 0x1,internal_format : 0x1, usage : 0x100. size=293760,pixel_stride=272,byte_stride=1088
10-11 23:28:37.445  6360  6423 D GRALLOC-ROCKCHIP: leave: prime_fd=90,share_attr_fd=95
10-11 23:28:37.528  6360  6396 D skia    : JPEG Decode 16
10-11 23:28:37.531  6360  6423 D GRALLOC-ROCKCHIP: leave, w : 270, h : 360, format : 0x1,internal_format : 0x1, usage : 0x100. size=391680,pixel_stride=272,byte_stride=1088
10-11 23:28:37.531  6360  6423 D GRALLOC-ROCKCHIP: leave: prime_fd=119,share_attr_fd=120
10-11 23:28:37.534  6360  6360 D ViewRootImpl[ReaderActivity]: changeCanvasOpacity: opaque=false
10-11 23:28:37.568  6360  6396 D OpenGLRenderer: Bitmap.cpp allocateHeapBitmap addr = ccc03bc0
10-11 23:28:37.569  6360  6396 D OpenGLRenderer: Bitmap.cpp allocateHeapBitmap addr = ccb83a00
10-11 23:28:37.572  6360  6371 I zygote  : NativeAlloc concurrent copying GC freed 12455(522KB) AllocSpace objects, 0(0B) LOS objects, 32% free, 12MB/18MB, paused 7.787ms total 371.348ms
10-11 23:28:37.575  6360  6423 D GRALLOC-ROCKCHIP: leave, w : 270, h : 270, format : 0x1,internal_format : 0x1, usage : 0x100. size=293760,pixel_stride=272,byte_stride=1088
10-11 23:28:37.575  6360  6423 D GRALLOC-ROCKCHIP: leave: prime_fd=118,share_attr_fd=129
10-11 23:28:37.590  6360  6418 D OpenGLRenderer: Bitmap.cpp allocateHeapBitmap addr = cc1cb1c0
10-11 23:28:37.608  6360  6418 D skia    : JPEG Decode 18
10-11 23:28:37.612  6360  6451 D OpenGLRenderer: Bitmap.cpp allocateHeapBitmap addr = ccbd4f40
10-11 23:28:37.648  6360  6396 D skia    : JPEG Decode 37
10-11 23:28:37.655  6360  6423 D GRALLOC-ROCKCHIP: leave, w : 700, h : 988, format : 0x1,internal_format : 0x1, usage : 0x100. size=2782208,pixel_stride=704,byte_stride=2816
10-11 23:28:37.655  6360  6423 D GRALLOC-ROCKCHIP: leave: prime_fd=147,share_attr_fd=148
10-11 23:28:37.693  6360  6396 D OpenGLRenderer: Bitmap.cpp allocateHeapBitmap addr = c8600000
10-11 23:28:37.698  6360  6396 D OpenGLRenderer: Bitmap.cpp allocateHeapBitmap addr = cbf00000
10-11 23:28:37.716  6360  6423 D GRALLOC-ROCKCHIP: leave, w : 700, h : 700, format : 0x1,internal_format : 0x1, usage : 0x100. size=1971200,pixel_stride=704,byte_stride=2816
10-11 23:28:37.716  6360  6423 D GRALLOC-ROCKCHIP: leave: prime_fd=146,share_attr_fd=150
10-11 23:28:37.841  6360  6371 I zygote  : NativeAlloc concurrent copying GC freed 5615(420KB) AllocSpace objects, 6(120KB) LOS objects, 32% free, 12MB/18MB, paused 210us total 263.541ms
10-11 23:28:38.126  6360  6371 I zygote  : NativeAlloc concurrent copying GC freed 868(153KB) AllocSpace objects, 5(244KB) LOS objects, 32% free, 12MB/18MB, paused 185us total 202.375ms
10-11 23:28:37.920  6360  6360 I chatty  : uid=10038(eu.kanade.tachiyomi.j2k) identical 3 lines
10-11 23:28:38.024  6360  6360 E jeffy   : applyEinkMode :eu.kanade.tachiyomi.j2k/eu.kanade.tachiyomi.ui.reader.ReaderActivity, dirty:Rect(0, 0 - 1404, 1872)
10-11 23:28:44.240  6360  6360 I zygote  : Deoptimizing void kotlinx.coroutines.JobSupport.removeNode$kotlinx_coroutines_core(kotlinx.coroutines.JobNode) due to JIT inline cache
10-11 23:28:44.245  6360  6360 I zygote  : Deoptimizing int kotlin.jvm.internal.TypeIntrinsics.getFunctionArity(java.lang.Object) due to JIT inline cache
10-11 23:28:44.279  6360  6360 E jeffy   : applyEinkMode :eu.kanade.tachiyomi.j2k/eu.kanade.tachiyomi.ui.reader.ReaderActivity, dirty:Rect(0, 0 - 1404, 1872)
10-11 23:28:44.298  6360  6450 D OpenGLRenderer: Bitmap.cpp allocateHeapBitmap addr = caa00000
10-11 23:28:44.381  6360  6360 I chatty  : uid=10038(eu.kanade.tachiyomi.j2k) identical 1 line
10-11 23:28:44.580  6360  6360 E jeffy   : applyEinkMode :eu.kanade.tachiyomi.j2k/eu.kanade.tachiyomi.ui.reader.ReaderActivity, dirty:Rect(0, 0 - 1404, 1872)
10-11 23:28:47.331  6360  6360 I zygote  : Deoptimizing kotlin.coroutines.CoroutineContext kotlinx.coroutines.CoroutineContextKt.newCoroutineContext(kotlinx.coroutines.CoroutineScope, kotlin.coroutines.CoroutineContext) due to JIT inline cache
10-11 23:28:47.331  6360  6360 I zygote  : Deoptimizing void kotlinx.coroutines.AbstractCoroutine.<init>(kotlin.coroutines.CoroutineContext, boolean, boolean) due to JIT inline cache
10-11 23:28:47.345  6360  6469 I zygote  : Deoptimizing java.lang.Object kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(kotlinx.serialization.DeserializationStrategy) due to JIT inline cache
10-11 23:28:47.345  6360  6396 I zygote  : Deoptimizing java.lang.Object kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(kotlinx.serialization.DeserializationStrategy) due to JIT inline cache
10-11 23:28:47.347  6360  6396 I zygote  : Deoptimizing java.lang.Object kotlinx.serialization.encoding.AbstractDecoder.decodeNullableSerializableElement(kotlinx.serialization.descriptors.SerialDescriptor, int, kotlinx.serialization.DeserializationStrategy, java.lang.Object) due to JIT inline cache
10-11 23:28:47.355  6360  6396 I zygote  : Deoptimizing java.lang.Object kotlinx.coroutines.JobSupport.tryMakeCompleting(java.lang.Object, java.lang.Object) due to JIT inline cache
10-11 23:28:47.358  6360  6360 E jeffy   : applyEinkMode :eu.kanade.tachiyomi.j2k/eu.kanade.tachiyomi.ui.reader.ReaderActivity, dirty:Rect(0, 0 - 1404, 1872)
--------- beginning of crash
10-11 23:28:47.365  6360  6396 E AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-1
10-11 23:28:47.365  6360  6396 E AndroidRuntime: Process: eu.kanade.tachiyomi.j2k, PID: 6360
10-11 23:28:47.365  6360  6396 E AndroidRuntime: kotlin.NotImplementedError: Unknown status: 0
10-11 23:28:47.365  6360  6396 E AndroidRuntime:        at eu.kanade.tachiyomi.data.track.bangumi.BangumiModelsKt.toBangumiStatus(SourceFile:40)
10-11 23:28:47.365  6360  6396 E AndroidRuntime:        at eu.kanade.tachiyomi.data.track.bangumi.BangumiApi$updateLibManga$2.invokeSuspend(Unknown Source:61)
10-11 23:28:47.365  6360  6396 E AndroidRuntime:        at eu.kanade.tachiyomi.data.track.bangumi.BangumiApi$updateLibManga$2.invoke(SourceFile:2)
10-11 23:28:47.365  6360  6396 E AndroidRuntime:        at eu.kanade.tachiyomi.data.track.bangumi.BangumiApi$updateLibManga$2.invoke(SourceFile:1)
10-11 23:28:47.365  6360  6396 E AndroidRuntime:        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Unknown Source:7)
10-11 23:28:47.365  6360  6396 E AndroidRuntime:        at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(SourceFile:54)
10-11 23:28:47.365  6360  6396 E AndroidRuntime:        at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:0)
10-11 23:28:47.365  6360  6396 E AndroidRuntime:        at eu.kanade.tachiyomi.util.system.CoroutinesExtensionsKt.withIOContext(Unknown Source:4)
10-11 23:28:47.365  6360  6396 E AndroidRuntime:        at eu.kanade.tachiyomi.data.track.bangumi.BangumiApi.updateLibManga(Unknown Source:6)
10-11 23:28:47.365  6360  6396 E AndroidRuntime:        at eu.kanade.tachiyomi.data.track.bangumi.Bangumi.update(Unknown Source:9)
10-11 23:28:47.365  6360  6396 E AndroidRuntime:        at eu.kanade.tachiyomi.util.chapter.ChapterTrackSyncKt.updateTrackChapterRead(SourceFile:2)
10-11 23:28:47.365  6360  6396 E AndroidRuntime:        at eu.kanade.tachiyomi.ui.reader.ReaderViewModel$updateTrackChapterAfterReading$1.invokeSuspend(Unknown Source:70)
10-11 23:28:47.365  6360  6396 E AndroidRuntime:        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:11)
10-11 23:28:47.365  6360  6396 E AndroidRuntime:        at kotlinx.coroutines.DispatchedTask.run(Unknown Source:93)
10-11 23:28:47.365  6360  6396 E AndroidRuntime:        at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(Unknown Source:3)
10-11 23:28:47.365  6360  6396 E AndroidRuntime:        at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
10-11 23:28:47.365  6360  6396 E AndroidRuntime:        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(Unknown Source:0)
10-11 23:28:47.365  6360  6396 E AndroidRuntime:        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:63)
10-11 23:28:47.394  6360  6365 I zygote  : Do full code cache collection, code=1019KB, data=657KB
10-11 23:28:47.397  6360  6365 I zygote  : After code cache collection, code=833KB, data=492KB
10-11 23:28:47.731  6360  6396 I zygote  : Deoptimizing java.lang.Object kotlin.coroutines.CombinedContext.fold(java.lang.Object, kotlin.jvm.functions.Function2) due to JIT inline cache
10-11 23:28:47.440  6360  6360 E jeffy   : applyEinkMode :eu.kanade.tachiyomi.j2k/eu.kanade.tachiyomi.ui.reader.ReaderActivity, dirty:Rect(0, 0 - 1404, 1872)
10-11 23:28:47.832  6360  6360 I zygote  : Deoptimizing void kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(kotlin.coroutines.Continuation, java.lang.Object, kotlin.jvm.functions.Function1) due to JIT inline cache
10-11 23:28:47.853  6360  6360 I zygote  : Deoptimizing void androidx.lifecycle.DefaultLifecycleObserverAdapter.onStateChanged(androidx.lifecycle.LifecycleOwner, androidx.lifecycle.Lifecycle$Event) due to JIT inline cache
10-11 23:28:47.861  6360  6360 I zygote  : Deoptimizing void androidx.appcompat.widget.AppCompatImageView.setImageDrawable(android.graphics.drawable.Drawable) due to JIT inline cache
10-11 23:28:47.866  6360  6360 I zygote  : Deoptimizing void kotlinx.coroutines.DispatchedTaskKt.resume(kotlinx.coroutines.DispatchedTask, kotlin.coroutines.Continuation, boolean) due to JIT inline cache
10-11 23:28:47.886  6360  6453 D OpenGLRenderer: Bitmap.cpp allocateHeapBitmap addr = cdd37940
10-11 23:28:48.035  6360  6360 D OpenGLRenderer: Bitmap.cpp allocateHeapBitmap addr = cf34fa00
10-11 23:28:48.038  6360  6360 D OpenGLRenderer: Bitmap.cpp allocateHeapBitmap addr = cf34fc00
10-11 23:28:48.055  6360  6360 I zygote  : Deoptimizing java.lang.Integer eu.kanade.tachiyomi.util.chapter.ChapterSort$sortComparator$sortFunction$2.invoke(eu.kanade.tachiyomi.data.database.models.Chapter, eu.kanade.tachiyomi.data.database.models.Chapter) due to JIT inline cache
10-11 23:28:48.063  6360  6360 I zygote  : Deoptimizing void eu.kanade.tachiyomi.ui.main.MainActivity.setupSearchTBMenu(android.view.Menu, boolean) due to JIT inline cache
10-11 23:28:48.177  6360  6360 I zygote  : Deoptimizing void androidx.recyclerview.widget.ChildHelper.detachViewFromParent(int) due to JIT inline cache
10-11 23:28:48.181  6360  6360 I zygote  : Deoptimizing void androidx.recyclerview.widget.RecyclerView$LayoutManager.addViewInt(android.view.View, int, boolean) due to JIT inline cache
10-11 23:28:48.279  6360  6423 D mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
10-11 23:28:48.592  6360  6360 I zygote  : Deoptimizing void androidx.lifecycle.DefaultLifecycleObserverAdapter.onStateChanged(androidx.lifecycle.LifecycleOwner, androidx.lifecycle.Lifecycle$Event) due to JIT inline cache
10-11 23:28:48.595  6360  6360 D OpenGLRenderer: Bitmap.cpp allocateHeapBitmap addr = ccf1b1c0
10-11 23:28:48.803  6360  6360 D OpenGLRenderer: Bitmap.cpp allocateHeapBitmap addr = ccab1140
10-11 23:28:48.935  6360  6360 E jeffy   : applyEinkMode :eu.kanade.tachiyomi.j2k/eu.kanade.tachiyomi.ui.main.MainActivity, dirty:Rect(0, 0 - 1404, 1872)
10-11 23:28:49.172  6360  6423 D GRALLOC-ROCKCHIP: leave, w : 1872, h : 1404, format : 0x1,internal_format : 0x1, usage : 0xb00. size=10513152,pixel_stride=1872,byte_stride=7488
10-11 23:28:49.173  6360  6423 D GRALLOC-ROCKCHIP: leave: prime_fd=152,share_attr_fd=153
10-11 23:28:49.175  6360  6423 D OpenGLRenderer: Bitmap.cpp allocateHeapBitmap addr = ccf07600
10-11 23:28:49.176  6360  6423 D OpenGLRenderer: Bitmap.cpp allocateHeapBitmap addr = ccaef000
10-11 23:28:49.178  6360  6423 D OpenGLRenderer: Bitmap.cpp allocateHeapBitmap addr = ccbee000
10-11 23:28:49.179  6360  6423 D OpenGLRenderer: Bitmap.cpp allocateHeapBitmap addr = ccbf2000
10-11 23:28:49.179  6360  6423 D OpenGLRenderer: Bitmap.cpp allocateHeapBitmap addr = cf2ee000
10-11 23:28:49.261  6360  6360 E jeffy   : applyEinkMode :eu.kanade.tachiyomi.j2k/eu.kanade.tachiyomi.ui.reader.ReaderActivity, dirty:Rect(0, 0 - 1404, 1872)
10-11 23:28:49.266  6360  6365 I zygote  : Do partial code cache collection, code=954KB, data=598KB
10-11 23:28:49.268  6360  6365 I zygote  : After code cache collection, code=927KB, data=585KB
10-11 23:28:49.268  6360  6365 I zygote  : Increasing code cache capacity to 3MB
10-11 23:28:49.342  6360  6360 W StaticLayout: maxLineHeight should not be -1.  maxLines:2 lineCount:2
10-11 23:28:49.344  6360  6360 I chatty  : uid=10038(eu.kanade.tachiyomi.j2k) identical 1 line
10-11 23:28:49.346  6360  6360 W StaticLayout: maxLineHeight should not be -1.  maxLines:2 lineCount:2
10-11 23:28:49.398  6360  6360 E jeffy   : applyEinkMode :eu.kanade.tachiyomi.j2k/eu.kanade.tachiyomi.ui.main.MainActivity, dirty:Rect(0, 0 - 1404, 1872)
10-11 23:28:49.437  6360  6423 D GRALLOC-ROCKCHIP: leave, w : 1872, h : 1404, format : 0x1,internal_format : 0x1, usage : 0xb00. size=10513152,pixel_stride=1872,byte_stride=7488
10-11 23:28:49.437  6360  6423 D GRALLOC-ROCKCHIP: leave: prime_fd=155,share_attr_fd=156
10-11 23:28:49.654  6360  6360 E jeffy   : applyEinkMode :eu.kanade.tachiyomi.j2k/eu.kanade.tachiyomi.ui.reader.ReaderActivity, dirty:Rect(0, 0 - 1404, 1872)
10-11 23:28:49.716  6360  6423 W libEGL  : EGLNativeWindowType 0xccf9e008 disconnect failed
10-11 23:28:49.734  6360  6360 I zygote  : Deoptimizing java.lang.Object androidx.arch.core.internal.SafeIterableMap.remove(java.lang.Object) due to JIT inline cache
10-11 23:28:49.735  6360  6360 I zygote  : Deoptimizing void kotlinx.coroutines.internal.LockFreeLinkedListNode.finishAdd(kotlinx.coroutines.internal.LockFreeLinkedListNode) due to JIT inline cache
10-11 23:28:49.739  6360  6360 I zygote  : Deoptimizing kotlinx.coroutines.channels.ChannelSegment kotlinx.coroutines.channels.BufferedChannel.completeClose(long) due to JIT inline cache
10-11 23:28:49.810  6360  6360 I zygote  : Deoptimizing kotlinx.coroutines.internal.LockFreeLinkedListNode kotlinx.coroutines.internal.LockFreeLinkedListNode.correctPrev() due to JIT inline cache
10-11 23:28:49.908  6360  6360 I zygote  : Deoptimizing boolean kotlinx.coroutines.JobSupport.cancelImpl$kotlinx_coroutines_core(java.lang.Object) due to JIT same target
10-11 23:28:49.909  6360  6360 I zygote  : Deoptimizing java.lang.Object kotlinx.coroutines.JobSupport.finalizeFinishingState(kotlinx.coroutines.JobSupport$Finishing, java.lang.Object) due to JIT same target
```

### TachiyomiJ2K version

1.7.4

### Android version

android8 and android9

### Device

elink reader and chromebook duet

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Tachiyomi](https://github.com/tachiyomiorg/tachiyomi)
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.7.4](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have updated all installed extensions.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by zanjie1999** [comment]
This PR seems to have fixed the issue https://github.com/Jays2Kings/tachiyomiJ2K/pull/1833
