### ISSUE TITLE
[Bug] App crashes when catalogue throws exception

### ISSUE THREAD

**Issue by arkon** [Jays2Kings/tachiyomiJ2K#46]
### Device information
* Tachiyomi version: 0.9.6
* Android version: 9

## Steps to reproduce
1. Install latest Manga Rock extension (1.2.16)
2. Go to Manga Rock catalogue

### Expected behavior
Shows snackbar with error message.

### Actual behavior
App crashes.

### Other details

<details>
<summary>Logcat</summary>

```
2020-01-09 19:57:40.007 26977-26977/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: eu.kanade.tachiyomi.j2k, PID: 26977
    rx.exceptions.OnErrorNotImplementedException: rootWindowInsets must not be null
        at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:386)
        at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:383)
        at rx.internal.util.ActionSubscriber.onError(ActionSubscriber.java:44)
        at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:153)
        at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:115)
        at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:212)
        at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
        at rx.internal.operators.OperatorTake$1.onNext(OperatorTake.java:79)
        at rx.internal.operators.OnSubscribeFilter$FilterSubscriber.onNext(OnSubscribeFilter.java:76)
        at rx.internal.operators.OperatorSwitch$SwitchSubscriber.drain(OperatorSwitch.java:314)
        at rx.internal.operators.OperatorSwitch$SwitchSubscriber.emit(OperatorSwitch.java:205)
        at rx.internal.operators.OperatorSwitch$InnerSubscriber.onNext(OperatorSwitch.java:399)
        at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
        at rx.internal.operators.NotificationLite.accept(NotificationLite.java:135)
        at rx.subjects.SubjectSubscriptionManager$SubjectObserver.emitNext(SubjectSubscriptionManager.java:253)
        at rx.subjects.BehaviorSubject.onNext(BehaviorSubject.java:160)
        at nucleus.presenter.RxPresenter.onTakeView(RxPresenter.java:321)
        at nucleus.presenter.Presenter.takeView(Presenter.java:154)
        at eu.kanade.tachiyomi.ui.base.presenter.NucleusConductorDelegate.onTakeView(NucleusConductorDelegate.kt:34)
        at eu.kanade.tachiyomi.ui.base.presenter.NucleusConductorLifecycleListener.postCreateView(NucleusConductorLifecycleListener.kt:10)
        at com.bluelinelabs.conductor.Controller.inflate(Controller.java:1019)
        at com.bluelinelabs.conductor.ControllerChangeHandler.executeChange(ControllerChangeHandler.java:190)
        at com.bluelinelabs.conductor.ControllerChangeHandler.executeChange(ControllerChangeHandler.java:154)
        at com.bluelinelabs.conductor.Router.performControllerChange(Router.java:813)
        at com.bluelinelabs.conductor.Router.performControllerChange(Router.java:783)
        at com.bluelinelabs.conductor.Router.performControllerChange(Router.java:765)
        at com.bluelinelabs.conductor.Router.pushController(Router.java:182)
        at eu.kanade.tachiyomi.ui.catalogue.CatalogueController.openCatalogue(CatalogueController.kt:177)
        at eu.kanade.tachiyomi.ui.catalogue.CatalogueController.onItemClick(CatalogueController.kt:152)
        at eu.davidea.viewholders.FlexibleViewHolder.onClick(FlexibleViewHolder.java:122)
        at android.view.View.performClick(View.java:6669)
        at android.view.View.performClickInternal(View.java:6638)
        at android.view.View.access$3100(View.java:789)
        at android.view.View$PerformClick.run(View.java:26145)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6898)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.IllegalStateException: rootWindowInsets must not be null
        at eu.kanade.tachiyomi.util.ViewExtensionsKt.snack(ViewExtensions.kt:50)
        at eu.kanade.tachiyomi.ui.catalogue.browse.BrowseCatalogueController.onAddPageError(BrowseCatalogueController.kt:399)
        at eu.kanade.tachiyomi.ui.catalogue.browse.BrowseCataloguePresenter$requestNext$4.invoke(BrowseCataloguePresenter.kt:165)
        at eu.kanade.tachiyomi.ui.catalogue.browse.BrowseCataloguePresenter$requestNext$4.invoke(BrowseCataloguePresenter.kt:32)
        at eu.kanade.tachiyomi.ui.base.presenter.BasePresenter$sam$rx_functions_Action2$0.call(Unknown Source:2)
        at nucleus.presenter.delivery.Delivery.split(Delivery.java:28)
```

</details>

**Comment by Jays2Kings** [comment]
Good catch, I didn't update manga rock for extension update testing, fixed now
