### ISSUE TITLE
[Bug] Multiple WebViews silently crash the app

### ISSUE THREAD

**Issue by sharedkestrel** [Jays2Kings/tachiyomiJ2K#568]
Sometimes Android warns me that TachiJ2K keeps crashing, with this as the log:

```
time: 1598082185096
msg: java.lang.RuntimeException: Using WebView from more than one process at once with the same data directory is not supported. https://crbug.com/558377 
stacktrace: java.lang.RuntimeException: Using WebView from more than one process at once with the same data directory is not supported. https://crbug.com/558377
 	at org.chromium.android_webview.AwBrowserProcess.b(PG:12)
 	at Ig.m(PG:30)
 	at Hg.run(PG:2)
 	at org.chromium.base.task.TaskRunnerImpl.g(PG:11)
 	at qw.run(Unknown Source:2)
 	at android.os.Handler.handleCallback(Handler.java:873)
 	at android.os.Handler.dispatchMessage(Handler.java:99)
 	at android.os.Looper.loop(Looper.java:193)
 	at android.app.ActivityThread.main(ActivityThread.java:6698)
 	at java.lang.reflect.Method.invoke(Native Method)
 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:859)
```
 
It doesn't seem to happen at the same time as the update checks.

**Comment by Caio99BR** [comment]
Duplicate of #556, maybe already fixed on latest release
