### ISSUE TITLE
[Bug] Pressing the display settings button crashes the app

### ISSUE THREAD

**Issue by d4rky-pl** [Jays2Kings/tachiyomiJ2K#697]
### Device information
* Tachiyomi version: 1.0.11
* Android phone & version: Samsung Galaxy Tab S6, Android 10

## Steps to reproduce
1. Open any manga, manhwa etc.
2. Tap to show the menu
3. Press the display settings button 
<img width="124" alt="Screenshot 2021-03-29 at 20 16 22" src="https://user-images.githubusercontent.com/284395/112881902-8c822680-90cc-11eb-9ac4-a9988192e990.png">

### Expected behavior
The app does not crash and settings menu is displayed

### Actual behavior
The app crashes.

### Other details
Logs from the moment of crash:

```
03-29 20:15:19.042 27043 27043 E ACRA    : ACRA caught a InflateException for eu.kanade.tachiyomi.j2k
03-29 20:15:19.042 27043 27043 E ACRA    : android.view.InflateException: Binary XML file line #2 in eu.kanade.tachiyomi.j2k:layout/reader_paged_layout: Index: 15, Size: 5
03-29 20:15:19.042 27043 27043 E ACRA    : Caused by: java.lang.IndexOutOfBoundsException: Index: 15, Size: 5
03-29 20:15:19.042 27043 27043 E ACRA    : 	at java.util.ArrayList.get(ArrayList.java:437)
03-29 20:15:19.042 27043 27043 E ACRA    : 	at androidx.appcompat.view.menu.MenuBuilder.getItem(MenuBuilder.java:752)
03-29 20:15:19.042 27043 27043 E ACRA    : 	at eu.kanade.tachiyomi.ui.reader.settings.ReaderSpinnerView.popup(ReaderSpinnerView.kt:201)
03-29 20:15:19.042 27043 27043 E ACRA    : 	at eu.kanade.tachiyomi.ui.reader.settings.ReaderSpinnerView.makeSettingsPopup(ReaderSpinnerView.kt:113)
03-29 20:15:19.042 27043 27043 E ACRA    : 	at eu.kanade.tachiyomi.ui.reader.settings.ReaderSpinnerView.bindToIntPreference(ReaderSpinnerView.kt:86)
03-29 20:15:19.042 27043 27043 E ACRA    : 	at eu.kanade.tachiyomi.ui.reader.settings.ReaderSpinnerView.bindToIntPreference$default(ReaderSpinnerView.kt:81)
03-29 20:15:19.042 27043 27043 E ACRA    : 	at eu.kanade.tachiyomi.ui.reader.settings.ReaderPagedView.initGeneralPreferences(ReaderPagedView.kt:34)
03-29 20:15:19.042 27043 27043 E ACRA    : 	at eu.kanade.tachiyomi.widget.BaseTabbedScrollView.onFinishInflate(BaseTabbedScrollView.kt:25)
03-29 20:15:19.042 27043 27043 E ACRA    : 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1134)
03-29 20:15:19.042 27043 27043 E ACRA    : 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
03-29 20:15:19.042 27043 27043 E ACRA    : 	at android.view.LayoutInflater.inflate(LayoutInflater.java:680)
03-29 20:15:19.042 27043 27043 E ACRA    : 	at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
03-29 20:15:19.042 27043 27043 E ACRA    : 	at android.view.LayoutInflater.inflate(LayoutInflater.java:479)
03-29 20:15:19.042 27043 27043 E ACRA    : 	at android.view.View.inflate(View.java:28552)
03-29 20:15:19.042 27043 27043 E ACRA    : 	at eu.kanade.tachiyomi.ui.reader.settings.TabbedReaderSettingsSheet.<init>(TabbedReaderSettingsSheet.kt:24)
03-29 20:15:19.042 27043 27043 E ACRA    : 	at eu.kanade.tachiyomi.ui.reader.ReaderActivity.onOptionsItemSelected(ReaderActivity.kt:289)
03-29 20:15:19.042 27043 27043 E ACRA    : 	at android.app.Activity.onMenuItemSelected(Activity.java:4326)
03-29 20:15:19.042 27043 27043 E ACRA    : 	at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:340)
03-29 20:15:19.042 27043 27043 E ACRA    : 	at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:264)
03-29 20:15:19.042 27043 27043 E ACRA    : 	at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
03-29 20:15:19.042 27043 27043 E ACRA    : 	at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
03-29 20:15:19.042 27043 27043 E ACRA    : 	at androidx.appcompat.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:65)
03-29 20:15:19.042 27043 27043 E ACRA    : 	at androidx.appcompat.widget.Toolbar$1.onMenuItemClick(Toolbar.java:207)
03-29 20:15:19.042 27043 27043 E ACRA    : 	at androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:779)
03-29 20:15:19.042 27043 27043 E ACRA    : 	at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:834)
03-29 20:15:19.042 27043 27043 E ACRA    : 	at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
03-29 20:15:19.042 27043 27043 E ACRA    : 	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:985)
03-29 20:15:19.042 27043 27043 E ACRA    : 	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:975)
03-29 20:15:19.042 27043 27043 E ACRA    : 	at androidx.appcompat.widget.ActionMenuView.invokeItem(ActionMenuView.java:623)
03-29 20:15:19.042 27043 27043 E ACRA    : 	at androidx.appcompat.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:151)
03-29 20:15:19.042 27043 27043 E ACRA    : 	at android.view.View.performClick(View.java:8160)
03-29 20:15:19.042 27043 27043 E ACRA    : 	at android.widget.TextView.performClick(TextView.java:16221)
03-29 20:15:19.042 27043 27043 E ACRA    : 	at android.view.View.performClickInternal(View.java:8137)
03-29 20:15:19.042 27043 27043 E ACRA    : 	at android.view.View.access$3700(View.java:888)
03-29 20:15:19.042 27043 27043 E ACRA    : 	at android.view.View$PerformClick.run(View.java:30236)
03-29 20:15:19.042 27043 27043 E ACRA    : 	at android.os.Handler.handleCallback(Handler.java:938)
03-29 20:15:19.042 27043 27043 E ACRA    : 	at android.os.Handler.dispatchMessage(Handler.java:99)
03-29 20:15:19.042 27043 27043 E ACRA    : 	at android.os.Looper.loop(Looper.java:246)
03-29 20:15:19.042 27043 27043 E ACRA    : 	at android.app.ActivityThread.main(ActivityThread.java:8506)
03-29 20:15:19.042 27043 27043 E ACRA    : 	at java.lang.reflect.Method.invoke(Native Method)
03-29 20:15:19.042 27043 27043 E ACRA    : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
03-29 20:15:19.042 27043 27043 E ACRA    : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

**Comment by Jays2Kings** [comment]
This will be fixed in the next version. For now you will have to disable webtoon side padding for the setting to work correctly

**Comment by d4rky-pl** [comment]
@Jays2Kings awesome, thanks for the workaround!
