### ISSUE TITLE
[Bug] Crashes when using bangumi to sync

### ISSUE THREAD

**Issue by in-out** [Jays2Kings/tachiyomiJ2K#820]
### Device information
* Tachiyomi version: 1.0.17
* Android phone & version: oneui 391

## Steps to reproduce
1. using bangumi to sync read status
2. between chapters

### Expected behavior
do not crash

**Comment by LiRunZhe** [comment]
same result
I tried original Tachiyomi and everything is good, hope it can be fixed soon.

**Comment by Jays2Kings** [comment]
Go to settings, advanced, dump crash logs, then attach that file here. That way I can see why that issue is happening

**Comment by in-out** [comment]
> Go to settings, advanced, dump crash logs, then attach that file here. That way I can see why that issue is happening

thanks for reply
here is crash log 
--------- beginning of main
05-20 13:07:00.092 21694 21694 E e.tachiyomi.j2: Invalid ID 0x00000000.
05-20 13:07:36.581 21694 32492 E Image   : /home/jitpack/build/library/src/main/jni/image/image.c(38): Library init func bmp_init failed
05-20 13:07:50.859 21694  7685 E ACRA    : ACRA caught a NotImplementedError for eu.kanade.tachiyomi.j2k
05-20 13:07:50.859 21694  7685 E ACRA    : kotlin.NotImplementedError: Unknown status
05-20 13:07:50.859 21694  7685 E ACRA    : 	at eu.kanade.tachiyomi.data.track.bangumi.BangumiModelsKt.toBangumiStatus(BangumiModels.kt:11)
05-20 13:07:50.859 21694  7685 E ACRA    : 	at eu.kanade.tachiyomi.data.track.bangumi.BangumiApi$updateLibManga$2.invokeSuspend(BangumiApi.kt:47)
05-20 13:07:50.859 21694  7685 E ACRA    : 	at eu.kanade.tachiyomi.data.track.bangumi.BangumiApi$updateLibManga$2.invoke(Unknown Source:10)
05-20 13:07:50.859 21694  7685 E ACRA    : 	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
05-20 13:07:50.859 21694  7685 E ACRA    : 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:165)
05-20 13:07:50.859 21694  7685 E ACRA    : 	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
05-20 13:07:50.859 21694  7685 E ACRA    : 	at eu.kanade.tachiyomi.data.track.bangumi.BangumiApi.updateLibManga(BangumiApi.kt:39)
05-20 13:07:50.859 21694  7685 E ACRA    : 	at eu.kanade.tachiyomi.data.track.bangumi.Bangumi.update(Bangumi.kt:42)
05-20 13:07:50.859 21694  7685 E ACRA    : 	at eu.kanade.tachiyomi.ui.reader.ReaderPresenter$updateTrackChapterRead$1$1.invokeSuspend(ReaderPresenter.kt:870)
05-20 13:07:50.859 21694  7685 E ACRA    : 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
05-20 13:07:50.859 21694  7685 E ACRA    : 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
05-20 13:07:50.859 21694  7685 E ACRA    : 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
05-20 13:07:50.859 21694  7685 E ACRA    : 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
05-20 13:07:50.859 21694  7685 E ACRA    : 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
05-20 13:07:50.859 21694  7685 E ACRA    : 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
05-20 13:07:51.419 32730 32730 E hiyomi.j2k:acr: Not starting debugger since process cannot load the jdwp agent.
--------- beginning of system
05-20 13:08:00.566 31233 31233 E e.tachiyomi.j2: Not starting debugger since process cannot load the jdwp agent.
05-20 13:08:00.736 31233 31233 E e.tachiyomi.j2: Invalid ID 0x00000000.
05-20 13:08:00.840 31233 31233 E e.tachiyomi.j2: Invalid ID 0x00000000.
05-20 13:08:00.886 31233   726 E SQLiteLog: (284) automatic index on C(manga_id)
05-20 13:08:00.886 31233   726 E SQLiteLog: (284) automatic index on R(manga_id)
05-20 13:08:00.886 31233   726 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
05-20 13:08:10.939 31233   919 E SQLiteLog: (284) automatic index on mangas(_id)

**Comment by dyphire** [comment]
will it be fixed?

**Comment by dyphire** [comment]
@Jays2Kings this is my crash log, Hope this can helps
```

App version: 1.4.4 (standard, af77722f6, 86, 2021-12-21T20:12:28.0641618)
Android version: 11 (SDK 30)
Android build ID: RP1A.200720.012.G9880ZCS3DUL3
Device brand: samsung
Device manufacturer: samsung
Device name: z3q
Device model: SM-G9880
Device product name: z3qzcx--------- beginning of main
01-01 23:42:12.947 23936 23936 E e.tachiyomi.j2: Not starting debugger since process cannot load the jdwp agent.
01-01 23:42:13.405 23936  4374 E SQLiteLog: (284) automatic index on C(manga_id)
01-01 23:42:13.405 23936  4374 E SQLiteLog: (284) automatic index on R(manga_id)
01-01 23:42:13.405 23936  4374 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
01-01 23:42:13.410 23936  4372 E SQLiteLog: (284) automatic index on C(manga_id)
01-01 23:42:13.410 23936  4372 E SQLiteLog: (284) automatic index on mangas(_id)
01-01 23:42:18.027 23936 23936 E SurfaceFlinger: resetPartialBlurMask failed to transact: -1
01-01 23:42:26.067 23936 23936 E SurfaceFlinger: resetPartialBlurMask failed to transact: -1
01-01 23:42:29.512 23936 23936 E SurfaceFlinger: resetPartialBlurMask failed to transact: -1
01-01 23:42:49.940 23936 23936 E SurfaceFlinger: resetPartialBlurMask failed to transact: -1
01-01 23:42:52.687 23936 23936 E SurfaceFlinger: resetPartialBlurMask failed to transact: -1
01-01 23:42:56.134 23936 23936 E SurfaceFlinger: resetPartialBlurMask failed to transact: -1
01-01 23:43:02.169 23936  4370 E SQLiteLog: (284) automatic index on mangas(_id)
01-01 23:46:02.371 23936 23936 E SurfaceFlinger: resetPartialBlurMask failed to transact: -1
01-01 23:54:07.430 23936 23936 E SurfaceFlinger: resetPartialBlurMask failed to transact: -1
01-01 23:56:08.883  7369  7369 E e.tachiyomi.j2: Not starting debugger since process cannot load the jdwp agent.
--------- beginning of system
01-01 23:56:09.258  7369 13745 E SQLiteLog: (284) automatic index on C(manga_id)
01-01 23:56:09.258  7369 13745 E SQLiteLog: (284) automatic index on R(manga_id)
01-01 23:56:09.258  7369 13745 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
01-01 23:56:14.602  7369  7369 E SurfaceFlinger: resetPartialBlurMask failed to transact: -1
01-01 23:57:36.587  7369  7369 E SurfaceFlinger: resetPartialBlurMask failed to transact: -1
01-01 23:57:41.089  7369  7369 E SurfaceFlinger: resetPartialBlurMask failed to transact: -1
```

**Comment by jareddo-kun** [comment]
Seems like the bug is still present in 1.6.0

[Crash log](https://paste.c-net.org/TahitiAmazon) 
5.67MB dump (https://paste.c-net.org/TahitiAmazon) 

The error started around the snippet below (located near the end of the log) 
`eu.kanade.tachiyomi.data.track.bangumi.BangumiApi$updateLibManga$2.invokeSuspend(BangumiApi.kt:60)`

**Comment by NeKoOuO** [comment]
Crash in the newest version
